import {test,expect} from "@playwright/test";
import {readFile} from "node:fs/promises";

test("crear pedido abre modal, permite cancelar y buscar cliente antes de confirmar",async({page})=>{
 const credentials=JSON.parse(await readFile(".runtime/e2e-credentials.json","utf8"));
 await page.goto("/login");
 await page.getByLabel("Correo electrónico",{exact:true}).fill(credentials.email);
 await page.getByLabel("Contraseña",{exact:true}).fill(credentials.password);
 await page.getByRole("button",{name:"Iniciar sesión",exact:true}).click();
 await expect(page).toHaveURL(/dashboard/);
 const tag=Date.now(),customer=`Cliente modal ${tag}`,brand=`Marca modal ${tag}`,project=`Proyecto modal ${tag}`;
 await page.goto("/clientes");
 await page.getByLabel("Nombre *",{exact:true}).fill(customer);
 await page.getByRole("button",{name:"Guardar cliente",exact:true}).click();
 await expect(page.getByRole("status")).toHaveText("Guardado correctamente.");
 await page.goto("/filamentos");
 await page.getByLabel("Marca *",{exact:true}).fill(brand);
 await page.getByLabel("Modelo *",{exact:true}).fill("PLA");
 await page.getByLabel("Color *",{exact:true}).fill("Verde limón");
 await page.getByLabel("Precio del rollo (COP) *",{exact:true}).fill("100000");
 await page.getByRole("button",{name:"Guardar filamento",exact:true}).click();
 await expect(page.getByRole("status")).toHaveText("Guardado correctamente.");
 await page.goto("/cotizaciones/nueva");
 await page.getByLabel("Nombre del proyecto *",{exact:true}).fill(project);
 await page.getByRole("combobox",{name:"Filamento *",exact:true}).fill(brand);
 await page.getByRole("option",{name:new RegExp(brand)}).click();
 await page.getByLabel("Gramos *",{exact:true}).fill("10");
 await page.getByLabel("Horas",{exact:true}).fill("1");
 await page.getByRole("button",{name:/Medio ·/}).click();
 await page.getByRole("button",{name:"Guardar y emitir cotización",exact:true}).click();
 await expect(page).toHaveURL(/cotizaciones\/[0-9a-f-]+$/);
 await page.getByRole("button",{name:"Aceptar cotización",exact:true}).click();
 await page.getByRole("button",{name:"Crear pedido",exact:true}).click();
 const modal=page.getByRole("dialog",{name:"Crear pedido",exact:true});
 await expect(modal).toBeVisible();
 await expect(modal.getByRole("button",{name:"Confirmar y crear pedido",exact:true})).toBeDisabled();
 await modal.getByRole("button",{name:"Cancelar",exact:true}).click();
 await expect(modal).not.toBeVisible();
 await page.getByRole("button",{name:"Crear pedido",exact:true}).click();
 await modal.getByRole("combobox",{name:"Cliente *",exact:true}).fill(customer);
 await page.getByRole("option",{name:customer,exact:true}).click();
 await expect(modal.locator("summary")).toHaveCount(0);
 await page.screenshot({path:".runtime/quote-order-modal-desktop.png"});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:".runtime/quote-order-modal-mobile.png"});
 await modal.getByRole("button",{name:"Confirmar y crear pedido",exact:true}).click();
 await expect(page).toHaveURL(/pedidos\/[0-9a-f-]+$/);
 await expect(page.getByText(project,{exact:true}).first()).toBeVisible();
 await page.goto("/pedidos/nuevo");
 await page.getByLabel("Proyecto *",{exact:true}).fill(project+" provisional");
 await page.getByLabel("Cliente *",{exact:true}).selectOption({label:customer});
 await page.getByRole("button",{name:"Crear pedido",exact:true}).click();
 await expect(page).toHaveURL(/pedidos\/[0-9a-f-]+$/);
 const intakeUrl=page.url(),intakeId=intakeUrl.split("/").at(-1)!;
 await page.goto("/cotizaciones/nueva");
 await page.getByLabel("Nombre del proyecto *",{exact:true}).fill(project+" provisional");
 await page.getByRole("combobox",{name:"Cliente",exact:true}).fill(customer);
 await page.getByRole("option",{name:customer,exact:true}).click();
 await page.getByRole("combobox",{name:"Filamento *",exact:true}).fill(brand);
 await page.getByRole("option",{name:new RegExp(brand)}).click();
 await page.getByLabel("Gramos *",{exact:true}).fill("10");
 await page.getByLabel("Horas",{exact:true}).fill("1");
 await page.getByRole("button",{name:/Medio ·/}).click();
 await page.getByRole("button",{name:"Guardar y emitir cotización",exact:true}).click();
 await expect(page).toHaveURL(/cotizaciones\/[0-9a-f-]+$/);
 await page.getByRole("button",{name:"Aceptar cotización",exact:true}).click();
 await page.getByRole("button",{name:"Crear pedido",exact:true}).click();
 await expect(modal.getByRole("combobox",{name:"Cliente *",exact:true})).toHaveValue(customer);
 await modal.locator("summary").click();
 await modal.getByLabel("Pedido ya registrado",{exact:true}).selectOption(intakeId);
 await modal.getByRole("button",{name:"Vincular pedido",exact:true}).click();
 await expect(page).toHaveURL(intakeUrl);
 await expect(page.getByRole("button",{name:"Iniciar impresión",exact:true})).toBeVisible();
});
