import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {ArrowRight,ArrowUpRight,Box,CheckCheck,ClipboardList,FilePlus2,Layers,PackageCheck,Plus,Printer,TriangleAlert,Users,Wallet,type LucideIcon} from "lucide-react";
import {getWorkspaceData} from "@/lib/app-service";
import {todayBogota} from "@/lib/dates";
import {metricSignal} from "@/lib/metric-signal";
import {money,display,oneDecimal} from "@/components/display";
import {DashboardPeriod} from "@/components/dashboard-period";
import {Badge} from "@/components/ui/badge";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";

const states=[{key:"not_started",label:"Sin empezar",icon:Box},{key:"printing",label:"Imprimiendo",icon:Printer},{key:"finished",label:"Terminados",icon:PackageCheck},{key:"delivered",label:"Entregados",icon:CheckCheck},{key:"closed",label:"Cerrados",icon:ClipboardList},{key:"damaged",label:"Daños / fallos",icon:TriangleAlert}];
function Indicator({title,value,metric,context,icon:Icon}:{title:string;value:unknown;metric:string;context:string;icon:LucideIcon}){
 const signal=metricSignal(metric,value);
 return <article className="home-indicator" data-tone={signal.tone}><div className="home-indicator-head"><h2>{title}</h2><span><Icon/></span></div><strong>{metric==="receivables"?money(value):display(value??0)}</strong><div className="home-indicator-foot"><span>{context}</span><small>{signal.label}</small></div></article>;
}
export async function DashboardPage({start="",end=""}:{start?:string;end?:string}){
 let report,orders;
 try{[report,orders]=await Promise.all([getWorkspaceData("dashboard","",start&&end?`${start}:${end}`:""),getWorkspaceData("orders","","",{limit:8,sort:"date_desc",start,end:end||todayBogota()})]);}
 catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar Inicio</AlertTitle><AlertDescription>Revisa el período e intenta nuevamente.</AlertDescription></Alert>;}
 const m=report.metrics??{},admin=report.access.role==="administrator";
 const actions=[{href:"/cotizaciones/nueva",title:"Crear cotización",detail:"Material, tiempo y acabados",icon:FilePlus2},{href:"/pedidos/nuevo",title:"Nuevo pedido",detail:"Registrar un proyecto",icon:Plus},{href:"/clientes",title:"Clientes",detail:"Contactos e historial",icon:Users},...(admin?[{href:"/finanzas",title:"Revisar finanzas",detail:"Resultados, cartera y caja",icon:Wallet}]:[])];
 return <div className="home-dashboard"><PageHeader title="Inicio" breadcrumbs={[{label:"Inicio"}]}/><DashboardPeriod key={`${start}:${end}`} start={start} end={end}/>
  {Boolean(m.provisional)&&<section className="home-notice"><TriangleAlert/><div><h2>Resultado provisional en revisión</h2><p>Hay pedidos entregados con costos incompletos. La utilidad sigue siendo provisional.</p></div><Link href="/pedidos">Revisar pedidos<ArrowRight/></Link></section>}
  <section className="home-indicators" aria-label="Indicadores del taller"><Indicator title="Pedidos" value={m.totalOrders} metric="totalOrders" context="Por fecha del pedido" icon={Box}/><Indicator title="Imprimiendo" value={m.printing} metric="printing" context="Producción en curso" icon={Printer}/><Indicator title="Terminados" value={m.finished} metric="finished" context="Pendientes de entrega" icon={PackageCheck}/><Indicator title={admin?"Cartera global":"Cerrados"} value={admin?m.receivables:m.closed} metric={admin?"receivables":"closed"} context={admin?"Saldo de pedidos confirmados":"Pedidos finalizados"} icon={admin?Wallet:CheckCheck}/></section>
  <section className="home-cycle"><header><h2><Layers/>Ciclo de producción del taller</h2><span>{display(m.totalOrders??0)} {Number(m.totalOrders)===1?"pedido":"pedidos"} en el período</span></header><div className="home-cycle-grid">{states.map(({key,label,icon:Icon})=>{const signal=metricSignal(key,m[key]);return <Link href={`/pedidos?filter=${key}`} data-tone={signal.tone} key={key}><div><span className="home-state-icon"><Icon/></span><strong>{display(m[key]??0)}</strong></div><h3>{label}</h3><small>{signal.label}</small></Link>;})}</div></section>
  <div className="home-main-grid"><section className="home-recent"><header><div><h2>Pedidos recientes</h2><p>Proyecto, cliente y estado actual.</p></div><Link href="/pedidos">Ver todos<ArrowUpRight/></Link></header>{orders.items.length?<div className="home-table-wrap" role="region" aria-label="Pedidos recientes" tabIndex={0}><Table><TableHeader><TableRow><TableHead>Pedido</TableHead><TableHead>Proyecto y detalle</TableHead><TableHead>Estado</TableHead>{admin&&<TableHead>Valor acordado</TableHead>}<TableHead><span className="sr-only">Abrir pedido</span></TableHead></TableRow></TableHeader><TableBody>{orders.items.map(i=>{const materials=(i.cardMaterials??[]) as Record<string,unknown>[];return <TableRow key={String(i.id)}><TableCell><Link className="home-order-code" href={`/pedidos/${i.id}`}>{String(i.code)}</Link></TableCell><TableCell><strong className="home-project">{String(i.title)}</strong><small className="home-customer">{String(i.customer??"Sin cliente")}</small>{materials.length>0&&<small className="home-material">{materials.map(mat=>{const f=mat.filamentSnapshot as Record<string,unknown>;return `${String(f.materialType??"")} ${String(f.color??"")} · ${oneDecimal(mat.grams)} g`;}).join(" / ")}</small>}</TableCell><TableCell><Badge variant="secondary" data-status={String(i.status)}>{display(i.status)}</Badge>{!i.confirmedAt&&<small className="home-customer">Provisional</small>}</TableCell>{admin&&<TableCell className="home-order-price">{money(i.agreedPrice)}<small>COP</small></TableCell>}<TableCell><Link className="home-open-order" href={`/pedidos/${i.id}`} aria-label={`Abrir ${i.code}`}><ArrowRight/></Link></TableCell></TableRow>;})}</TableBody></Table></div>:<div className="home-empty"><Box/><h3>No hay pedidos en este período</h3><p>Cambia el período o registra un nuevo proyecto.</p></div>}<footer><div><strong>¿Una nueva impresión en cola?</strong><span>Prepara el material, el tiempo y el precio del proyecto.</span></div><Link href="/cotizaciones/nueva"><FilePlus2/>Crear cotización</Link></footer></section><aside className="home-actions"><header><h2>Acciones del taller</h2><p>Accesos directos para tu trabajo diario.</p></header><div>{actions.map(({href,title,detail,icon:Icon})=><Link href={href} key={href}><span className="home-action-icon"><Icon/></span><span><strong>{title}</strong><small>{detail}</small></span><ArrowUpRight/></Link>)}</div></aside></div>
 </div>;
}
