import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {ArrowLeft,CalendarDays,Info,Wallet,History,SquarePen,Ban,CircleCheck} from "lucide-react";
import {getEntityDetail,getWorkspaceData} from "@/lib/app-service";
import {money} from "@/components/display";
import {ExpenseEditor} from "@/components/expense-editor";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";

const dateLabel=(value:unknown)=>new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"long",year:"numeric",timeZone:"America/Bogota"}).format(new Date(String(value).length===10?String(value)+"T12:00:00-05:00":String(value)));
const timestamp=(value:unknown)=>new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Bogota"}).format(new Date(String(value)));
export async function ExpenseDetail({id}:{id:string}){
 let data;try{data=await getEntityDetail("expenses",id);}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar el gasto</AlertTitle><AlertDescription>Vuelve al listado e intenta de nuevo.</AlertDescription></Alert>;}
 const {item,related}=data,voided=Boolean(item.voidedAt),operating=item.classification==="opex";
 const users=voided?[]:(await getWorkspaceData("users")).items.filter(u=>u.active).map(u=>({value:String(u.userId??u.id),label:String(u.name)}));
 return <div className="expense-detail-page">
  
  <PageHeader title={String(item.description)} breadcrumbs={[{label:"Gastos",href:"/gastos"},{label:"Detalle del gasto"}]} badges={<span className={voided?"expense-record-state voided":"expense-record-state"}>{voided?<Ban aria-hidden="true"/>:<CircleCheck aria-hidden="true"/>}{voided?"Registro anulado":"Registro vigente"}</span>} description={<><CalendarDays aria-hidden="true"/>Fecha: {dateLabel(item.expenseDate)} · {String(item.category)} · {operating?"Gasto operativo":"Compra de material"}{operating?" · "+(item.costBehavior==="fixed"?"Fijo":"Variable"):""}</>} actions={<div className="app-header-amount"><span>Monto registrado</span><strong>{money(item.amount)} <small>COP</small></strong></div>}/>
  <div className="expense-detail-grid"><div className="expense-detail-information">
   <section className="expense-detail-panel"><header><div><Info aria-hidden="true"/><h2>Información del gasto</h2></div><span>Datos registrados</span></header><dl>
    <div><dt>Descripción</dt><dd>{String(item.description)}</dd></div><div><dt>Valor contabilizado</dt><dd>{money(item.amount)} COP</dd></div><div><dt>Fecha del gasto</dt><dd>{String(item.expenseDate)}</dd></div><div><dt>Categoría</dt><dd>{String(item.category)}</dd></div><div><dt>Clasificación</dt><dd>{operating?"Gasto operativo":"Compra de material"}</dd></div><div><dt>Comportamiento</dt><dd>{operating?(item.costBehavior==="fixed"?"Fijo":"Variable"):"No aplica"}</dd></div><div className="expense-detail-full"><dt>Responsable</dt><dd><span className="expense-responsible-avatar">{String(item.responsibleName).split(" ").filter(Boolean).slice(0,2).map(w=>w[0]).join("")}</span>{String(item.responsibleName)}</dd></div><div className="expense-detail-full"><dt>Notas internas</dt><dd className="expense-detail-notes">{String(item.notes||"Sin notas registradas.")}</dd></div>
   </dl>{voided&&<div className="expense-void-reason"><Ban aria-hidden="true"/><div><strong>Registro anulado</strong><p>{String(item.voidReason)}</p></div></div>}</section>
   <section className="expense-detail-panel expense-impact"><header><div><Wallet aria-hidden="true"/><h2>Impacto en tus finanzas</h2></div></header><div className="expense-impact-values"><div><span>Gastos operativos</span><strong>{money(voided||!operating?"0":item.amount)}</strong></div><div><span>Salida de caja</span><strong>{money(voided?"0":item.amount)}</strong></div></div><p>{voided?"Este registro ya no afecta los resultados ni la caja.":operating?"Se reconoce en la fecha del gasto y reduce la utilidad del período correspondiente.":"Registra la salida de caja por compra de material. El costo del producto se toma de la cotización."}</p></section>
   <section className="expense-detail-panel expense-audit"><header><div><History aria-hidden="true"/><h2>Historial del registro</h2></div></header><ol>{related.audit?.map(event=>{const metadata=event.metadata as Record<string,unknown>;return <li key={String(event.id)}><strong>{event.action==="expenses.update"?"Registro corregido":event.action==="expenses.void"?"Registro anulado":event.action==="create"?"Registro creado":event.action==="correct"?"Corrección registrada":String(event.action)}</strong><span>{timestamp(event.occurredAt)} · {String(event.actorName)}</span>{Boolean(metadata?.reason)&&<p>{String(metadata.reason)}</p>}</li>;})}</ol>{Boolean(item.correctionOfId)&&<Link href={`/gastos/${item.correctionOfId}`}>Ver registro original <ArrowLeft aria-hidden="true"/></Link>}{related.corrections?.map(c=><Link key={String(c.id)} href={`/gastos/${c.id}`}>Ver registro corregido: {String(c.description)}</Link>)}</section>
  </div><section className="expense-detail-panel expense-detail-edit"><header><div><SquarePen aria-hidden="true"/><h2>{voided?"Registro cerrado":"Corregir gasto"}</h2></div>{!voided&&<span>Modo corrección</span>}</header>{voided?<p className="expense-locked-message">Este registro conserva los datos originales. Puedes consultar su historial y, si existe, el registro corregido.</p>:<><p className="expense-correction-help">Indica el motivo y actualiza los datos. La corrección conserva el registro original en el historial.</p><ExpenseEditor key={String(item.version)} item={item} responsibles={users}/></>}</section></div>
 </div>;
}
