import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {Wallet,Plug,Wrench,CalendarDays,Search,Plus,ArrowRight,ChevronLeft,ChevronRight,Info} from "lucide-react";
import {getWorkspaceData} from "@/lib/app-service";
import {todayBogota} from "@/lib/dates";
import {money} from "@/components/display";
import {ExpenseCreate} from "@/components/expense-create";
import {ExpenseListControls} from "@/components/expense-list-controls";
import {Card,CardHeader,CardTitle,CardContent} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
import {InputGroup,InputGroupInput,InputGroupAddon} from "@/components/ui/input-group";
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from "@/components/ui/table";

type Expense=Record<string,unknown>;
function Classification({item}:{item:Expense}){return <div className="expense-classification"><Badge variant="outline" data-tone={item.classification==="material_purchase"?"info":item.costBehavior==="variable"?"warning":"gold"}>{item.classification==="material_purchase"?"Compra de material":item.costBehavior==="fixed"?"Operativo fijo":"Operativo variable"}</Badge><small>{String(item.category)}</small></div>;}
function Responsible({item}:{item:Expense}){const name=String(item.responsibleName);return <span className="expense-responsible"><span>{name.split(/\s+/).slice(0,2).map(p=>p[0]).join("").toUpperCase()}</span>{name}</span>;}
function Open({item}:{item:Expense}){return <Link className="customer-open" href={`/gastos/${item.id}`} aria-label={`Abrir gasto ${item.description}`}>Abrir<ArrowRight aria-hidden="true"/></Link>;}

export async function ExpensesList({q="",filter="",page="1",sort="date",view="table",start,end}:{q?:string;filter?:string;page?:string;sort?:string;view?:string;start?:string;end?:string}){
 const today=todayBogota(),from=start??today.slice(0,7)+"-01",until=end??today;
 let data,users;try{[data,users]=await Promise.all([getWorkspaceData("expenses",q,filter,{page:Number(page),sort,limit:25,start:from,end:until}),getWorkspaceData("users")]);}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar los gastos</AlertTitle><AlertDescription>Revisa las fechas del período e intenta de nuevo.</AlertDescription><Link href="/gastos">Volver a este mes</Link></Alert>;}
 const m=data.metrics??{},current=data.page??1,pages=data.pages??1;
 const params={q,filter,sort,view,start:from,end:until},href=(next:number)=>"?"+new URLSearchParams({...params,page:String(next)}).toString();
 const responsibles=users.items.filter(u=>u.active).map(u=>({value:String(u.userId??u.id),label:String(u.name)}));
 const kpis=[{label:"Total del período",value:money(m.totalExpenses),detail:`Compras de material: ${money(m.materialPurchases)}`,tone:"gold",icon:Wallet},{label:"Gastos operativos fijos",value:money(m.fixedExpenses),detail:"Servicios, arriendo y otros gastos fijos",tone:"info",icon:Plug},{label:"Gastos operativos variables",value:money(m.variableExpenses),detail:"Mantenimiento e insumos clasificados variables",tone:"warning",icon:Wrench},{label:"Promedio diario",value:money(m.dailyAverage),detail:m.periodDays?`Total dividido entre ${m.periodDays} días del período`:"Selecciona una fecha de inicio para calcularlo",tone:"gold",icon:CalendarDays}];
 return <div className={`customers-page expenses-page ${view==="cards"?"expense-view-cards":"expense-view-table"}`}>
 <PageHeader title="Gastos y costos operativos" breadcrumbs={[{label:"Gastos"}]} badges={<Badge variant="secondary">{String(m.periodCount??0)} en el período</Badge>} actions={<Button variant="outline" render={<a href="#registrar-gasto"/>} nativeButton={false}><Plus/>Registrar gasto</Button>}/>
 <form className="expense-period" aria-label="Período de gastos"><span><CalendarDays aria-hidden="true"/>Período</span><label htmlFor="expense-from">Desde<Input id="expense-from" name="start" type="date" defaultValue={from} max={today}/></label><label htmlFor="expense-until">Hasta<Input id="expense-until" name="end" type="date" defaultValue={until} max={today}/></label><input type="hidden" name="q" value={q}/><input type="hidden" name="filter" value={filter}/><input type="hidden" name="sort" value={sort}/><input type="hidden" name="view" value={view}/><Button type="submit" variant="outline">Aplicar período</Button><Link href={`?${new URLSearchParams({...params,start:today.slice(0,7)+"-01",end:today})}`}>Este mes</Link><Link href={`?${new URLSearchParams({...params,start:"",end:today})}`}>Todo</Link></form>
 <section className="customer-indicators expense-indicators" aria-label="Indicadores de gastos">{kpis.map(({label,value,detail,tone,icon:Icon})=><article key={label} data-tone={tone}><header><h2>{label}</h2><span><Icon aria-hidden="true"/></span></header><div><strong>{value}</strong></div><p>{detail}</p></article>)}</section>
 <div className="customers-workspace"><section className="expense-directory" aria-label="Listado de gastos"><div className="expense-toolbar"><form className="customer-search" role="search"><label htmlFor="expense-search" className="sr-only">Buscar gastos</label><InputGroup><InputGroupAddon><Search/></InputGroupAddon><InputGroupInput id="expense-search" name="q" defaultValue={q} placeholder="Buscar descripción, categoría o responsable"/></InputGroup>{Object.entries(params).filter(([key])=>key!=="q").map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<Button type="submit" variant="outline">Buscar</Button>{q&&<Link href={`?${new URLSearchParams({...params,q:""})}`}>Limpiar</Link>}</form><ExpenseListControls categories={m.categories as string[]??[]} start={from} end={until}/></div>
 <div className="customer-results"><div className="customer-result-heading"><h2>Registro de gastos</h2><span>{data.total} {q||filter?"encontrados":"registros"}</span></div>{!data.items.length?<div className="customer-empty"><Wallet/><h3>{q||filter?"Sin gastos con esos filtros":"No hay gastos en este período"}</h3><p>{q||filter?"Prueba otra búsqueda o categoría.":"Registra un egreso o selecciona otro período."}</p></div>:<>
 <div className="customer-table-wrap expense-table-wrap" role="region" aria-label="Tabla de gastos" tabIndex={0}><Table><TableHeader><TableRow>{["Fecha","Descripción y detalle","Clasificación / Categoría","Responsable","Monto (COP)","Detalle"].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{data.items.map(item=><TableRow key={String(item.id)}><TableCell><time dateTime={String(item.expenseDate)}>{String(item.expenseDate)}</time></TableCell><TableCell><strong className="expense-description">{String(item.description)}</strong>{Boolean(item.notes)&&<small className="expense-note">{String(item.notes)}</small>}</TableCell><TableCell><Classification item={item}/></TableCell><TableCell><Responsible item={item}/></TableCell><TableCell><strong className="expense-amount">{money(item.amount)}</strong></TableCell><TableCell><Open item={item}/></TableCell></TableRow>)}</TableBody></Table></div>
 <div className="expense-cards">{data.items.map(item=><article key={String(item.id)}><header><time>{String(item.expenseDate)}</time><strong className="expense-amount">{money(item.amount)}</strong></header><h3>{String(item.description)}</h3><Classification item={item}/>{Boolean(item.notes)&&<p>{String(item.notes)}</p>}<footer><Responsible item={item}/><Open item={item}/></footer></article>)}</div></>}
 <nav className="customer-pagination" aria-label="Paginación de gastos"><Button variant="outline" disabled={current<=1} render={<Link href={href(current-1)}/>} nativeButton={false}><ChevronLeft/>Anterior</Button><span>Página {current} de {pages}</span><Button variant="outline" disabled={current>=pages} render={<Link href={href(current+1)}/>} nativeButton={false}>Siguiente<ChevronRight/></Button></nav></div>
 <div className="customer-help"><Info aria-hidden="true"/><p><strong>Impacto en tus finanzas.</strong> Los gastos operativos afectan la utilidad del período. Las compras de material registran la salida de caja y no duplican el costo del producto cotizado.</p></div></section>
 <Card id="registrar-gasto" className="customer-create expense-create"><CardHeader><div><CardTitle><span/>Registrar gasto</CardTitle><Wallet aria-hidden="true"/></div><p>Ingresa los datos del egreso. Los campos con <span>*</span> son obligatorios.</p></CardHeader><CardContent><ExpenseCreate today={today} userId={data.access.userId} responsibles={responsibles}/></CardContent></Card></div></div>;
}
