import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {Banknote,Wallet,ChartNoAxesColumn,TrendingUp,Users,ArrowUpRight,TriangleAlert,Plus,Target} from "lucide-react";
import {getWorkspaceData} from "@/lib/app-service";
import {todayBogota} from "@/lib/dates";
import {money,percentage,display,statusLabels} from "@/components/display";
import {metricSignal} from "@/lib/metric-signal";
import {PeriodToolbar} from "@/components/report-page";
import {FinanceChart} from "@/components/finance-chart";
import {FinancialRecords} from "@/components/financial-records";
import {CommandForm} from "@/components/command-form";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
import {Button} from "@/components/ui/button";
import {Card,CardHeader,CardTitle,CardContent,CardDescription} from "@/components/ui/card";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";

const labels:Record<string,string>={sales:"Ventas de pedidos entregados",directCosts:"Costo de productos entregados",grossProfit:"Utilidad bruta",grossMargin:"Margen bruto",opex:"Gastos operativos",independentLosses:"Pérdidas independientes",netProfit:"Utilidad neta operativa",receipts:"Recaudo del período",cohortReceipts:"Recaudo de pedidos entregados",collectionRate:"Cobro de entregas",receivables:"Cartera global",cashIn:"Entradas de caja",cashOut:"Salidas de caja",cashNet:"Flujo de caja neto",failedCosts:"Costos de intentos fallidos",breakEven:"Punto de equilibrio del período",breakEvenProgress:"Avance del equilibrio"};
const value=(key:string,v:unknown)=>v===null||v===undefined?"Sin base":/Margin|Rate|Progress/.test(key)?percentage(v):money(v);
function Rows({keys,metrics}:{keys:string[];metrics:Record<string,unknown>}){return <dl className="finance-analysis-rows">{keys.map(key=><div key={key}><dt>{labels[key]}</dt><dd data-tone={metricSignal(key,metrics[key]).tone}>{value(key,metrics[key])}</dd></div>)}</dl>;}
export async function FinancePage({start="",end=""}:{start?:string;end?:string}){
 let data;try{data=await getWorkspaceData("finance","",start&&end?start+":"+end:"");}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar Finanzas</AlertTitle><AlertDescription>Revisa el período e intenta de nuevo.</AlertDescription></Alert>;}
 const metrics=data.metrics??{},cash=(data as unknown as {cashMovements?:Record<string,unknown>[]}).cashMovements??[];
 const progress=metrics.breakEvenProgress===null||metrics.breakEvenProgress===undefined?null:Math.max(0,Math.min(100,Number(metrics.breakEvenProgress)));
 return <div className="finance-page">
  <PageHeader title="Finanzas" breadcrumbs={[{label:"Finanzas"}]} description="Resultados del período, cartera y caja en pesos colombianos." actions={<Button render={<Link href="/gastos"/>} nativeButton={false}><Plus data-icon="inline-start"/>Registrar gasto</Button>}/>
  <PeriodToolbar start={start} end={end}/>
  <section className="finance-kpis" aria-label="Indicadores financieros">{[{key:"sales",icon:Banknote,detail:"Pedidos entregados en el período"},{key:"netProfit",icon:TrendingUp,detail:"Después de costos, gastos y pérdidas"},{key:"receivables",icon:Wallet,detail:"Saldo de pedidos confirmados al cierre"},{key:"cashNet",icon:ChartNoAxesColumn,detail:"Entradas menos salidas del período"}].map(({key,icon:Icon,detail})=>{const signal=metricSignal(key,metrics[key]);return <article key={key} data-tone={signal.tone}><header><h2>{labels[key]}</h2><Icon aria-hidden="true"/></header><strong>{money(metrics[key])}<small>COP</small></strong><span className="finance-kpi-signal">{signal.label}</span><p>{detail}</p></article>;})}</section>
  <Card className="finance-comparison"><CardHeader><div><CardTitle>Ventas, cobros, costos y utilidad</CardTitle><CardDescription>Cobrado muestra los pagos recibidos de los pedidos entregados en el período, hasta la fecha de corte.</CardDescription></div><span className="finance-chart-unit">COP · Pesos colombianos</span></CardHeader><CardContent><FinanceChart metrics={metrics}/></CardContent></Card>
  <div className="finance-analysis-grid">
   <Card><CardHeader><div><CardTitle>Rentabilidad</CardTitle><CardDescription>Pedidos entregados en el período</CardDescription></div><TrendingUp aria-hidden="true"/></CardHeader><CardContent><Rows keys={["sales","directCosts","grossProfit","grossMargin","opex","independentLosses"]} metrics={metrics}/><div className="finance-analysis-total" data-tone={metricSignal("netProfit",metrics.netProfit).tone}><span>Utilidad neta operativa</span><strong>{money(metrics.netProfit)}</strong></div></CardContent></Card>
   <Card><CardHeader><div><CardTitle>Recaudo y caja</CardTitle><CardDescription>Pagos y desembolsos por su fecha real</CardDescription></div><Wallet aria-hidden="true"/></CardHeader><CardContent><Rows keys={["receipts","cohortReceipts","collectionRate","receivables","cashIn","cashOut"]} metrics={metrics}/><div className="finance-analysis-total" data-tone={metricSignal("cashNet",metrics.cashNet).tone}><span>Flujo de caja neto</span><strong>{money(metrics.cashNet)}</strong></div></CardContent></Card>
   <Card><CardHeader><div><CardTitle>Equilibrio y producción</CardTitle><CardDescription>Costos, cobertura y pedidos</CardDescription></div><Target aria-hidden="true"/></CardHeader><CardContent><Rows keys={["failedCosts","breakEven","breakEvenProgress"]} metrics={metrics}/>{progress!==null?<div className="finance-equilibrium" role="progressbar" aria-label="Avance del equilibrio" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} aria-valuetext={percentage(metrics.breakEvenProgress)}><span style={{width:progress+"%"}}/></div>:<p className="finance-no-base">Falta una base de ventas con contribución positiva para calcular el equilibrio.</p>}<div className="finance-production">{["not_started","printing","finished","delivered","closed","damaged"].map(key=><Link key={key} href={`/pedidos?filter=${key}`} data-tone={metricSignal(key,metrics[key]).tone}><span>{statusLabels[key]}</span><strong>{display(metrics[key]??0)}</strong></Link>)}</div><p className="finance-production-total">{display(metrics.totalOrders??0)} pedidos por fecha del pedido</p></CardContent></Card>
  </div>
  <Card className="finance-customers"><CardHeader><div><CardTitle>Clientes y gestión de cartera</CardTitle><CardDescription>Ventas entregadas del período y saldo pendiente al cierre.</CardDescription></div><Link href="/clientes">Ver clientes <ArrowUpRight aria-hidden="true"/></Link></CardHeader><CardContent>{data.items.length?<Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Pedidos confirmados</TableHead><TableHead>Ventas del período</TableHead><TableHead>Saldo por cobrar</TableHead><TableHead>Estado de cartera</TableHead><TableHead>Último pedido</TableHead></TableRow></TableHeader><TableBody>{data.items.map(c=>{const pending=Number(c.balance)>0;return <TableRow key={String(c.id)}><TableCell><Link href={`/clientes/${c.id}`} className="finance-client-link"><span className="finance-client-avatar">{String(c.name).split(" ").filter(Boolean).slice(0,2).map(w=>w[0]).join("")}</span>{String(c.name)}</Link></TableCell><TableCell>{display(c.orderCount)}</TableCell><TableCell>{money(c.totalSales)}</TableCell><TableCell data-tone={pending?"warning":"positive"}>{money(c.balance)}</TableCell><TableCell><span className="finance-customer-status" data-tone={pending?"warning":"positive"}>{pending?"Pendiente de cobro":"Sin saldo pendiente"}</span></TableCell><TableCell>{display(c.lastOrder)}</TableCell></TableRow>;})}</TableBody></Table>:<div className="finance-empty"><Users aria-hidden="true"/><strong>Aún no hay clientes para comparar</strong><p>Las ventas aparecerán al entregar los primeros pedidos.</p></div>}</CardContent></Card>
  <div className="finance-bottom"><Card className="finance-loss-form"><CardHeader><div><CardTitle><TriangleAlert aria-hidden="true"/>Registrar pérdida independiente</CardTitle><CardDescription>Para pérdidas que no pertenecen a un pedido.</CardDescription></div></CardHeader><CardContent><CommandForm command="losses.create" fields={[{name:"recognizedDate",label:"Fecha",type:"date",value:todayBogota(),required:true},{name:"category",label:"Categoría",required:true},{name:"description",label:"Descripción",required:true},{name:"amount",label:"Valor (COP)",type:"number",min:"1",step:"1",required:true},{name:"cashOutDate",label:"Fecha del desembolso (si se pagó)",type:"date"},{name:"cashOutAmount",label:"Desembolso efectivo (COP, opcional)",type:"number",min:"1",step:"1",help:"Déjalo vacío si ya se pagó como compra o gasto."}]} label="Registrar pérdida"/><p className="finance-loss-note">No repitas costos ya registrados en pedidos, compras o gastos.</p></CardContent></Card><FinancialRecords cash={cash} start={start} end={end}/></div>
 </div>;
}
