import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {ArrowRight,Box,CalendarDays,CheckCircle2,ChevronLeft,ChevronRight,Coins,Plus,Printer,Search,Wallet} from "lucide-react";
import {getWorkspaceData} from "@/lib/app-service";
import {D} from "@/lib/finance";
import {todayBogota,timezone} from "@/lib/dates";
import {ListControls} from "@/components/list-controls";
import {FilamentColor} from "@/components/filament-color";
import {display,money,oneDecimal} from "@/components/display";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {InputGroup,InputGroupAddon,InputGroupInput} from "@/components/ui/input-group";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Alert,AlertDescription,AlertTitle} from "@/components/ui/alert";
type Item=Record<string,unknown>;
function Customer({item}:{item:Item}){const name=String(item.customer??"Sin cliente");return <div className="quote-list-customer"><span aria-hidden="true">{name.split(/\s+/).slice(0,2).map(w=>w[0]).join("").toUpperCase()}</span><strong>{name}</strong></div>;}
function Material({item}:{item:Item}){const lines=(item.cardMaterials??[]) as {grams:string;filamentSnapshot:Record<string,unknown>}[];if(!lines.length)return <span className="order-muted">{item.confirmedAt?"Sin material":"Sin cotización vinculada"}</span>;const f=lines[0].filamentSnapshot;return <div className="order-material"><span>{[f.materialType,f.brand,f.model].filter(Boolean).join(" · ")}</span><span>{Boolean(f.color)&&<FilamentColor value={f.color}/>}<span>{oneDecimal(lines.reduce((sum,line)=>sum.plus(line.grams),new D(0)).toString())} g</span></span>{lines.length>1&&<small>+ {lines.length-1} material{lines.length>2?"es":""}</small>}</div>;}
function Payment({item}:{item:Item}){const balance=item.balance,paid=balance!=null&&new D(String(balance)).isZero();return <div className="order-payment" data-tone={paid?"positive":balance==null?"neutral":"warning"}><strong>{money(balance)}</strong><small>{balance==null?"Precio por confirmar":paid?"Pagado":"Pendiente"}</small></div>;}
const deliveryFormatter=new Intl.DateTimeFormat("es-CO",{timeZone:timezone,day:"2-digit",month:"2-digit",year:"numeric"});
function Delivery({item,today}:{item:Item;today:string}){
 const delivered=["delivered","closed"].includes(String(item.status));
 const date=delivered?(item.deliveredAt?todayBogota(new Date(String(item.deliveredAt))):null):(item.promisedDeliveryDate?String(item.promisedDeliveryDate):null);
 const late=Boolean(date&&date<today&&!delivered);
 return <div className="order-delivery" data-late={late}><span>{date?<time dateTime={date}>{deliveryFormatter.format(new Date(date+"T12:00:00-05:00"))}</time>:delivered?"Fecha no registrada":"Sin fecha prevista"}</span>{date&&<small>{delivered?"Entrega realizada":late?"Entrega vencida":"Prevista"}</small>}</div>;
}
function Profit({item}:{item:Item}){const profit=item.agreedPrice==null?null:new D(String(item.agreedPrice)).minus(String(item.actualCost??0));return <div className="order-list-profit" data-tone={profit===null?"neutral":profit.isNegative()?"negative":"positive"}><strong>{profit?money(profit.toString()):"—"}</strong><small>{profit===null?"Precio por confirmar":"Ganancia"}</small></div>;}
function DetailLink({item}:{item:Item}){return <Link className="quote-register-detail" href={`/pedidos/${item.id}`}>Abrir detalle<ArrowRight aria-hidden="true"/></Link>;}
export async function OrdersList({q="",filter="",page="1",sort="date",view="table"}:{q?:string;filter?:string;page?:string;sort?:string;view?:string}){
 let data;try{data=await getWorkspaceData("orders",q,filter,{page:Number(page),sort,limit:25});}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar los pedidos</AlertTitle><AlertDescription>Intenta de nuevo o solicita ayuda al administrador.</AlertDescription></Alert>;}
 const m=data.metrics??{},current=data.page??1,pages=data.pages??1,href=(n:number)=>"?"+new URLSearchParams({q,filter,sort,view,page:String(n)}).toString();
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const kpis=[{label:"Valor de pedidos en curso",value:money(m.activeValue),note:"Pedidos pendientes de entrega · COP",icon:<Coins/>,tone:"neutral"},{label:"En fabricación",value:String(m.printing??0),note:"Pedidos imprimiendo",icon:<Printer/>,tone:"info"},{label:"Listos para entrega",value:String(m.finished??0),note:"Producción terminada",icon:<CheckCircle2/>,tone:"positive"},{label:"Saldo por cobrar",value:money(m.balance),note:"Descontando anticipos y abonos · COP",icon:<Wallet/>,tone:new D(String(m.balance??0)).isZero()?"positive":"warning"}];
 return <div className={"quotes-list-page orders-list-page "+(view==="cards"?"quotes-card-view":"quotes-table-view")}><PageHeader title="Pedidos" breadcrumbs={[{label:"Pedidos"}]} badges={<Badge variant="secondary">{String(m.active??0)} en curso</Badge>} actions={<Button render={<Link href="/pedidos/nuevo"/>} nativeButton={false}><Plus/>Nuevo pedido</Button>}/><section className="quotes-list-kpis" aria-label="Resumen de pedidos">{kpis.map(k=><article key={k.label} data-tone={k.tone}><div><span>{k.label}</span><span className="quotes-kpi-icon">{k.icon}</span></div><strong>{k.value}</strong><p>{k.note}</p></article>)}</section>
 <section className="quotes-list-toolbar" aria-label="Filtros de pedidos"><form role="search"><label htmlFor="orders-search" className="sr-only">Buscar en Pedidos</label><InputGroup><InputGroupAddon><Search/></InputGroupAddon><InputGroupInput id="orders-search" name="q" defaultValue={q} placeholder="Buscar por código, proyecto o cliente"/></InputGroup><input type="hidden" name="filter" value={filter}/><input type="hidden" name="view" value={view}/><input type="hidden" name="sort" value={sort}/><Button type="submit" variant="outline">Buscar</Button>{q&&<Link href={"?"+new URLSearchParams({filter,view,sort}).toString()}>Limpiar</Link>}</form><ListControls entity="orders"/></section>
 <section className="quotes-list-results" aria-label="Pedidos"><div className="quotes-list-result-count">{data.total} pedidos {q||filter?"encontrados":"registrados"}</div>{!data.items.length?<div className="quotes-list-empty"><Box/><h2>{q||filter?"Sin coincidencias":"Aún no hay pedidos"}</h2><p>{q||filter?"Prueba otra búsqueda o cambia el estado.":"Crea tu primer pedido para comenzar."}</p></div>:<><div className="quotes-list-table" role="region" aria-label="Tabla de pedidos" tabIndex={0}><Table><TableHeader><TableRow>{["Código","Proyecto / material","Cliente","Producción","Fecha de entrega","Valor total","Costo del producto","Ganancia","Saldo pendiente","Detalle"].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{data.items.map(i=><TableRow key={String(i.id)}><TableCell><Link className="quote-list-code" href={`/pedidos/${i.id}`}>{String(i.code)}</Link></TableCell><TableCell><div className="order-table-project"><strong>{String(i.title)}</strong><Material item={i}/></div></TableCell><TableCell><Customer item={i}/></TableCell><TableCell><Badge variant="secondary" data-status={String(i.status)}>{display(i.status)}</Badge>{!i.confirmedAt&&<small className="order-provisional">Provisional</small>}</TableCell><TableCell><Delivery item={i} today={today}/></TableCell><TableCell className="quote-list-total"><strong>{money(i.agreedPrice)}</strong><small>COP</small></TableCell><TableCell className="quote-list-total"><strong>{money(i.actualCost)}</strong><small>COP</small></TableCell><TableCell><Profit item={i}/></TableCell><TableCell><Payment item={i}/></TableCell><TableCell><div className="quote-list-row-actions"><DetailLink item={i}/></div></TableCell></TableRow>)}</TableBody></Table></div>
 <div className="quotes-list-cards">{data.items.map(i=><article className="quote-register-card order-register-card" data-status={String(i.status)} key={String(i.id)}><div className="quote-register-body"><div className="quote-register-heading"><div><Link className="quote-list-code" href={`/pedidos/${i.id}`}># {String(i.code)}</Link><h2><Link href={`/pedidos/${i.id}`}>{String(i.title)}</Link></h2></div><Badge variant="secondary" data-status={String(i.status)}><span className="quote-state-dot"/>{display(i.status)}</Badge></div><div className="quote-register-client"><Customer item={i}/>{!i.confirmedAt&&<span className="order-provisional">Provisional</span>}</div><div className="order-card-material"><Material item={i}/></div><dl className="order-card-dates"><div><dt><CalendarDays aria-hidden="true"/>Fecha del pedido</dt><dd><time dateTime={String(i.orderDate)}>{String(i.orderDate)}</time></dd></div><div><dt>{["delivered","closed"].includes(String(i.status))?"Fecha de entrega":"Entrega prevista"}</dt><dd><Delivery item={i} today={today}/></dd></div></dl><div className="order-card-profit"><div><span>Costo del producto</span><strong>{money(i.actualCost)}</strong></div><div><span>Ganancia</span><Profit item={i}/></div></div><div className="order-card-amounts"><div><span>Total del pedido</span><strong>{money(i.agreedPrice)}</strong><small>COP</small></div><div><span>Saldo pendiente</span><Payment item={i}/></div></div></div><footer className="quote-register-footer"><span className="order-received">Recibido {money(i.receivedAmount)}</span><DetailLink item={i}/></footer></article>)}</div></>}</section><nav className="record-pagination" aria-label="Paginación de pedidos"><Button disabled={current<=1} variant="outline" render={<Link href={href(Math.max(1,current-1))}/>} nativeButton={false}><ChevronLeft/>Anterior</Button><span>Página {current} de {pages}</span><Button disabled={current>=pages} variant="outline" render={<Link href={href(current+1)}/>} nativeButton={false}>Siguiente<ChevronRight/></Button></nav></div>;
}
