import {paymentMethodOptions} from "@/lib/payment-methods";
import {PageHeader} from "@/components/page-header";
import {OrderStatus} from "@/components/order-status";
import Link from "next/link";
import {Box,Layers,TrendingUp,Wallet} from "lucide-react";
import {OrderQuotePicker} from "@/components/order-quote-picker";
import {FilamentColor} from "@/components/filament-color";
import {getEntityDetail} from "@/lib/app-service";
import {D} from "@/lib/finance";
import {Summary} from "@/components/entity-detail";
import {CommandForm} from "@/components/command-form";
import {money,display,oneDecimal,unitMoney} from "@/components/display";
import {Card,CardHeader,CardTitle,CardContent} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
const date=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export async function OrderDetail({id}:{id:string}){
 let data;try{data=await getEntityDetail("orders",id);}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar el pedido</AlertTitle><AlertDescription>Intenta de nuevo o solicita ayuda al administrador.</AlertDescription></Alert>;}
 const {item,related,access}=data,admin=access.role==="administrator",order=true,quote=false,closed=Boolean(item.closedAt);
 const deliveryDate=item.deliveredAt?new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(String(item.deliveredAt))):date();
 const revision=related.linkedRevision?.[0];
 const price=item.agreedPrice==null?null:new D(String(item.agreedPrice)),actual=new D(String(item.actualCost??0)),profit=price?.minus(actual);
 const received=new D(String(item.receivedAmount??0)),paidPercent=price?.isPositive()?oneDecimal(received.div(price).times(100).toString()):null;
 const seconds=BigInt(String(revision?.printSeconds??0));
 const late=Boolean(item.promisedDeliveryDate&&String(item.promisedDeliveryDate)<date()&&!["delivered","closed"].includes(String(item.status)));
 return <div className="order-detail-page"><PageHeader title={<>Pedido {String(item.code)}</>} breadcrumbs={[{label:"Pedidos",href:"/pedidos"},{label:String(item.code)}]} badges={<><Badge variant="secondary" data-status={String(item.status)}>{display(item.status)}</Badge>{closed&&<Badge variant="outline">Solo consulta</Badge>}{!item.confirmedAt&&<Badge variant="outline">Provisional</Badge>}</>} description={paidPercent?<span className="order-header-payment">Recibido {paidPercent} % · {money(item.receivedAmount)}</span>:undefined}/>
 {Boolean(item.confirmedAt)&&<OrderStatus item={item} attempts={related.attempts??[]} seconds={seconds} deliveryDate={deliveryDate} today={date()}/>}
 <div className="order-detail-columns"><div className="order-detail-main">
 <Card className="order-overview"><CardHeader><div className="order-section-title"><span><Box/></span><CardTitle>Información general del pedido</CardTitle></div><code>{String(item.code)}</code></CardHeader><CardContent><dl className="order-overview-grid"><div><dt>Nombre de la pieza / proyecto</dt><dd>{String(item.title)}</dd>{revision&&<small>{String(revision.quantity??1)} {Number(revision.quantity??1)===1?"pieza":"piezas"}</small>}</div><div data-late={late}><dt>Entrega prevista</dt><dd>{item.promisedDeliveryDate?String(item.promisedDeliveryDate):"Sin fecha prevista"}</dd>{late&&<small>Entrega vencida</small>}</div></dl><div className="order-customer-strip"><div><span>Cliente</span><strong>{String(item.customerName??"Sin cliente")}</strong>{Boolean(item.customerPhone)&&<small>{String(item.customerPhone)}</small>}</div><div><span>Fecha del pedido</span><strong>{String(item.orderDate)}</strong></div></div><div className="order-note"><h3>Notas e instrucciones del taller</h3><p>{item.notes?String(item.notes):"Sin notas registradas."}</p></div>{!closed&&<details className="order-inline-editor"><summary>Editar pedido y valores</summary><div className="order-edit-grid"><section><h3>Datos del pedido</h3><CommandForm command="orders.updateMetadata" payload={{orderId:id,expectedVersion:item.version}} fields={[{name:"title",label:"Proyecto",value:String(item.title),required:true},{name:"promisedDeliveryDate",label:"Entrega prevista",type:"date",value:String(item.promisedDeliveryDate??"")},{name:"notes",label:"Notas",type:"textarea",value:String(item.notes??"")}]} label="Guardar datos"/></section>{admin&&Boolean(item.confirmedAt)&&<section><h3>Modificar costo y precio</h3><CommandForm command="orders.updateCommercial" payload={{orderId:id,expectedVersion:item.version}} fields={[{name:"estimatedCost",label:"Costo del producto (COP)",type:"number",min:"0",value:String(item.estimatedCost??"0"),required:true},{name:"agreedPrice",label:"Precio acordado con el cliente (COP)",type:"number",min:String(item.receivedAmount??"0"),step:"1",value:String(item.agreedPrice),required:true},{name:"reason",label:"Motivo del ajuste",required:true}]} label="Guardar valores"/></section>}</div></details>}</CardContent></Card>
 {revision&&<Card><CardHeader><div className="order-section-title" data-tone="info"><span><Layers/></span><CardTitle>Cotización vinculada y materiales</CardTitle></div>{revision&&<Link className="order-small-link" href={`/cotizaciones/${item.sourceQuoteId}`}>Ver cotización →</Link>}</CardHeader><CardContent>{revision?<><div className="order-quote-summary"><div><span>Revisión aceptada</span><strong>#{String(revision.revisionNumber)}</strong></div><div><span>Impresión estimada</span><strong>{String(seconds/3600n)} h {String(seconds%3600n/60n)} min</strong></div><div><span>Costo del producto</span><strong>{money(item.estimatedCost)}</strong></div></div><div className="order-detail-materials">{(related.materials??[]).map(m=>{const f=m.filamentSnapshot as Record<string,unknown>;return <article key={String(m.id)}><div><strong>{[f.brand,f.model,f.materialType].filter(Boolean).join(" · ")}</strong><FilamentColor value={f.color}/></div><div><strong>{oneDecimal(m.grams)} g</strong><small>{unitMoney(m.pricePerGram)}</small></div></article>;})}</div></>:<p className="order-muted">Vincula una cotización para confirmar el precio y habilitar producción, costos y abonos.</p>}</CardContent></Card>}
 {order&&!item.confirmedAt&&<Card><CardHeader><CardTitle>Cotización y precio del producto</CardTitle></CardHeader><CardContent><OrderQuotePicker orderId={id} customerId={String(item.customerId)} quotes={related.availableQuotes??[]}/></CardContent></Card>}
 {Boolean(item.confirmedAt)&&<Card className="order-profit-card"><CardHeader><div className="order-section-title" data-tone="positive"><span><TrendingUp/></span><CardTitle>Costo del producto y ganancia</CardTitle></div></CardHeader><CardContent><dl className="order-profit-metrics"><div><dt>Costo del producto</dt><dd>{money(item.actualCost)}</dd></div><div><dt>Precio acordado</dt><dd>{money(item.agreedPrice)}</dd></div><div data-tone={profit?.isNegative()?"negative":"positive"}><dt>Ganancia</dt><dd>{profit?money(profit.toString()):"—"}</dd></div></dl><p className="order-muted">{item.estimatedCostOverride!=null?"Costo ajustado en este pedido. Se conserva la cotización original.":"El costo proviene directamente de la cotización vinculada."}</p></CardContent></Card>}
 <div className="order-history"><Card><CardHeader><CardTitle>Historial del pedido</CardTitle></CardHeader><CardContent>{Object.entries(related).filter(([key,rows])=>["attempts","costs","payments","cashMovements"].includes(key)&&rows.length>0).map(([key,rows])=><details className="order-inline-editor" key={key}><summary>{({attempts:"Intentos de impresión",costs:"Registros anteriores de costos",payments:"Pagos",revisions:"Revisiones",orders:"Pedidos",quotes:"Cotizaciones",cashMovements:"Desembolsos directos"} as Record<string,string>)[key]??key} ({rows.length})</summary><div className="flex flex-col gap-5">{rows.map((row,index)=><article className="mobile-record" key={String(row.id??index)}><Summary item={row}/>{!closed&&admin&&key==="cashMovements"&&<details><summary className="inline-link">Corregir error del desembolso</summary><p className="text-sm text-muted-foreground">Corrige únicamente el registro. No representa un reintegro.</p><CommandForm command="cash.correctDirectOut" payload={{movementId:row.id,sourceId:row.directCostId??row.independentLossId,expectedVersion:row.version}} fields={[{name:"reason",label:"Motivo",required:true},{name:"voidFalseRecord",label:"Este desembolso nunca ocurrió; anular solo el registro falso",type:"checkbox"},{name:"date",label:"Fecha real",type:"date",value:String(row.businessDate),required:true},{name:"amount",label:"Valor real (COP)",type:"number",min:"1",step:"1",value:String(row.amount),required:true},{name:"reference",label:"Referencia",value:String(row.reference??"")}]} label="Guardar desembolso corregido"/></details>}{!closed&&admin&&key==="payments"&&<details><summary className="inline-link">Corregir error de registro</summary><p className="text-sm text-muted-foreground">Corrección de digitación; no representa una devolución. Conserva el registro original.</p><CommandForm command="payments.correct" payload={{paymentId:row.id}} fields={[{name:"reason",label:"Motivo de la corrección",required:true},{name:"voidFalseRecord",label:"Este pago nunca se recibió; anular solo el registro falso",type:"checkbox"},{name:"paymentDate",label:"Fecha real del pago",type:"date",value:String(row.paymentDate),required:true},{name:"amount",label:"Valor real (COP)",type:"number",min:"1",step:"1",value:String(row.amount),required:true},{name:"method",label:"Medio de pago",value:String(row.method??""),options:paymentMethodOptions(row.method)}]} label="Guardar corrección"/></details>}{row.revisionNumber!==undefined&&<p>Revisión {display(row.revisionNumber)}</p>}{quote&&key==="revisions"&&<Link className="inline-link" href={`/api/quotes/${id}/revisions/${row.id}/pdf`}>Descargar PDF de esta revisión</Link>}</article>)}</div></details>)}</CardContent></Card></div>
 </div><aside className="order-detail-sidebar"><Card className="order-account"><CardHeader><div className="order-section-title"><span><Wallet/></span><CardTitle>Estado de cuenta comercial</CardTitle></div><Badge variant="secondary">{item.confirmedAt?item.balance==="0"?"Pagado":"En curso":"Provisional"}</Badge></CardHeader><CardContent><div className="order-account-total"><span>Total acordado con el cliente</span><strong>{money(item.agreedPrice)} <small>COP</small></strong><dl><div><dt>Pagos recibidos</dt><dd>{money(item.receivedAmount)}</dd></div><div><dt>Saldo por cobrar</dt><dd>{money(item.balance)}</dd></div></dl></div>{!item.confirmedAt&&<p className="order-muted">El precio se confirma al vincular una cotización aceptada.</p>}{!closed&&admin&&Boolean(item.confirmedAt)&&Number(item.balance)>0&&<details className="order-inline-editor"><summary>Registrar abono</summary><div className="flex flex-col gap-4"><CommandForm command="payments.create" payload={{orderId:id}} fields={[{name:"paymentDate",label:"Fecha del pago",type:"date",value:date(),required:true},{name:"amount",label:"Valor recibido (COP)",type:"number",min:"1",step:"1",max:String(item.balance??""),required:true},{name:"method",label:"Medio de pago",options:paymentMethodOptions()},{name:"reference",label:"Referencia"}]} label="Guardar abono"/>{Number(item.balance)>0&&<CommandForm command="payments.settleBalance" payload={{orderId:id}} fields={[{name:"paymentDate",label:"Fecha del pago del saldo",type:"date",value:date(),required:true},{name:"method",label:"Medio de pago",options:paymentMethodOptions()}]} label={"Registrar saldo recibido: "+money(item.balance)}/>}</div></details>}</CardContent></Card>
 </aside></div></div>;
}

