"use client";
import {CustomerCombobox} from "@/components/customer-combobox";
import {PageHeader} from "@/components/page-header";
import {useRef,useState} from "react";
import Link from "next/link";
import {Plus,Save,Check,Copy,Clock,Layers,Trash2,Info,Coins,Paintbrush,TrendingUp,FileText} from "lucide-react";
import {useRouter} from "next/navigation";
import {useForm,useFieldArray,useWatch,Controller} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {z} from "zod";
import {action} from "@/app/actions";
import {D,calculateQuote,defaultFormula,durationSeconds,type QuoteInput} from "@/lib/finance";
import {money,decimalInput,oneDecimal} from "@/components/display";
import {Button} from "@/components/ui/button";
import {Card,CardHeader,CardTitle,CardContent,CardDescription} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Field,FieldGroup,FieldLabel,FieldDescription} from "@/components/ui/field";
import {ToggleGroup,ToggleGroupItem} from "@/components/ui/toggle-group";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
import {Spinner} from "@/components/ui/spinner";
const schema=z.object({projectName:z.string().min(1),customerId:z.string(),description:z.string(),hours:z.string().regex(/^\d+$/),minutes:z.string().regex(/^\d+$/).refine(v=>Number(v)<60),seconds:z.string().regex(/^\d+$/).refine(v=>Number(v)<60),materials:z.array(z.object({filamentId:z.string().min(1),grams:z.string().min(1),pricePerGram:z.string().min(1)})).min(1),postprocess:z.array(z.object({description:z.string().min(1),category:z.string(),amount:z.string().min(1)})),powerKw:z.string(),energyRate:z.string(),machineRate:z.string(),contingencyRate:z.string(),minimum:z.string(),medium:z.string(),high:z.string(),businessDate:z.string().min(1),validUntil:z.string(),customerNotes:z.string(),internalNotes:z.string(),manualPrice:z.string().regex(/^(?:|0|[1-9]\d{0,17})$/,"Usa un precio entero en COP.")});
type Values=z.infer<typeof schema>;
export function QuoteForm({customers,filaments,defaults,initial,quoteId,revisionId,version,status}:{initial?:QuoteInput;quoteId?:string;revisionId?:string;version?:unknown;status?:string;customers:Record<string,unknown>[];filaments:Record<string,unknown>[];defaults?:Record<string,unknown>}){
 const router=useRouter();const formula={...defaultFormula,...defaults,...initial?.formula};const [level,setLevel]=useState(initial?.selectedLevel??"");const [error,setError]=useState("");const key=useRef<string|null>(null);const intent=useRef<"draft"|"publish">("draft");const publishKey=useRef<string|null>(null);const [savedId,setSavedId]=useState("");const [copied,setCopied]=useState(false);
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const form=useForm<Values>({resolver:zodResolver(schema),defaultValues:{projectName:initial?.projectName??"",customerId:initial?.customerId??"",description:initial?.description??"",hours:String(BigInt(initial?.printSeconds??"0")/3600n),minutes:String(BigInt(initial?.printSeconds??"0")%3600n/60n),seconds:String(BigInt(initial?.printSeconds??"0")%60n),materials:initial?.materials.map(line=>({...line,grams:decimalInput(line.grams),pricePerGram:decimalInput(line.pricePerGram)}))??[{filamentId:"",grams:"",pricePerGram:""}],postprocess:initial?.postprocess??[],powerKw:new D(formula.powerKw).toString(),energyRate:new D(formula.energyRate).toString(),machineRate:new D(formula.machineRate).toString(),contingencyRate:new D(formula.contingencyRate).toString(),minimum:new D(formula.multipliers[0]).toString(),medium:new D(formula.multipliers[1]).toString(),high:new D(formula.multipliers[2]).toString(),businessDate:initial?.businessDate??today,validUntil:initial?.validUntil??"",customerNotes:initial?.customerNotes??"",internalNotes:initial?.internalNotes??"",manualPrice:initial?.manualPrice??""}});
 const materials=useFieldArray({control:form.control,name:"materials"});const post=useFieldArray({control:form.control,name:"postprocess"});const values=useWatch({control:form.control}) as Values;
 function input(v:Values):QuoteInput{return {projectName:v.projectName,...(v.customerId?{customerId:v.customerId}:{}),description:v.description,printSeconds:durationSeconds(v.hours,v.minutes,v.seconds),materials:v.materials,postprocess:v.postprocess,formula:{powerKw:v.powerKw,energyRate:v.energyRate,machineRate:v.machineRate,contingencyRate:v.contingencyRate,multipliers:[v.minimum,v.medium,v.high]},...(level?{selectedLevel:level as "minimum"|"medium"|"high"}:{}),...(v.manualPrice?{manualPrice:v.manualPrice}:{}),businessDate:v.businessDate,...(v.validUntil?{validUntil:v.validUntil}:{}),customerNotes:v.customerNotes,internalNotes:v.internalNotes};}
 const manualPriceValid=/^(?:|0|[1-9]\d{0,17})$/.test(values.manualPrice??"");
 let preview:ReturnType<typeof calculateQuote>|null=null;try{preview=calculateQuote({...input(values),manualPrice:manualPriceValid&&values.manualPrice?values.manualPrice:undefined});}catch{}
 async function save(v:Values){setError("");if(!level&&!v.manualPrice){setError("Selecciona un nivel o escribe un precio manual para esta cotización.");return;}try{key.current??=crypto.randomUUID();const result=await action(quoteId?(status==="draft"?"quotes.updateDraft":"quotes.revise"):"quotes.createDraft",{...input(v),...(quoteId?{quoteId,revisionId,expectedVersion:version}:{}),idempotencyKey:key.current});if(!result.ok)setError(result.error.message);else{const data=result.data as Record<string,unknown>;const id=String(data.quoteId??data.id);setSavedId(id);if(intent.current==="publish"){publishKey.current??=crypto.randomUUID();const issued=await action("quotes.publish",{quoteId:id,expectedVersion:quoteId?Number(version)+1:1,idempotencyKey:publishKey.current});if(!issued.ok){setError("El borrador se guardó, pero no se pudo emitir: "+issued.error.message);return;}}router.push("/cotizaciones/"+id);router.refresh();}}catch{setError("No pudimos confirmar el guardado. Reintenta la misma operación.");}}
 const actualPrice=preview&&manualPriceValid&&((level||values.manualPrice)?preview.selectedPrice:null)||null;const actualProfit=actualPrice!==null&&preview?new D(actualPrice).minus(preview.costProduction):null;const actualMargin=actualPrice!==null&&actualProfit&&!new D(actualPrice).isZero()?actualProfit.div(actualPrice).times(100).toFixed(2):null;
 function text(name:keyof Values,label:string,type="text"){const problem=form.formState.errors[name];return <Field className={name==="projectName"?"quote-project-name":name==="businessDate"||name==="validUntil"?"quote-project-date":undefined} data-invalid={!!problem}><FieldLabel htmlFor={"quote-"+name}>{label}</FieldLabel><Input id={"quote-"+name} type={type} {...form.register(name)} aria-invalid={!!problem} min={type==="number"?"0":undefined} step={type==="number"?"any":undefined}/>{problem&&<FieldDescription role="alert">Revisa este campo.</FieldDescription>}</Field>;}
 return <form onSubmit={event=>{intent.current=(event.nativeEvent as SubmitEvent).submitter?.getAttribute("data-intent")==="publish"?"publish":"draft";void form.handleSubmit(save)(event);}} onChange={()=>{key.current=null;publishKey.current=null;setCopied(false);}} className="quote-editor"><PageHeader title={quoteId?(status==="draft"?"Editar cotización":"Nueva revisión"):"Nueva cotización"} breadcrumbs={[{label:"Cotizaciones",href:"/cotizaciones"},{label:quoteId?"Editar":"Nueva"}]} badges={<span className="quote-edit-badge">En edición</span>} actions={<><Button type="button" variant="outline" onClick={()=>router.push("/cotizaciones")}>Descartar</Button><Button type="submit" variant="secondary" disabled={form.formState.isSubmitting} onClick={()=>{intent.current="draft";}}><Save data-icon="inline-start"/>Guardar borrador</Button></>}/><div className="quote-sections"><Card className="quote-project-card"><CardHeader><CardTitle>Información del proyecto</CardTitle></CardHeader><CardContent><FieldGroup className="quote-project-fields">{text("projectName","Nombre del proyecto *")}<Field><FieldLabel htmlFor="quote-customer">Cliente</FieldLabel><Controller name="customerId" control={form.control} render={({field})=><CustomerCombobox customers={customers} value={field.value} onBlur={field.onBlur} disabled={form.formState.isSubmitting} onChange={id=>{field.onChange(id);key.current=null;publishKey.current=null;setCopied(false);}}/>}/></Field><Field className="field-wide"><FieldLabel htmlFor="quote-description">Descripción / Detalles del modelo</FieldLabel><Textarea placeholder="Especificaciones, relleno, acabados o detalles del modelo…" id="quote-description" {...form.register("description")}/></Field>{text("businessDate","Fecha comercial *","date")}{text("validUntil","Válida hasta","date")}</FieldGroup></CardContent></Card>
 <Card className="quote-material-card"><CardHeader><CardTitle>Materiales y filamentos</CardTitle><CardDescription>Precio por gramo editable para esta cotización.</CardDescription></CardHeader><CardContent><FieldGroup>{materials.fields.map((row,index)=><FieldGroup key={row.id} className="quote-line"><Field><FieldLabel htmlFor={"filament-"+index}>Filamento *</FieldLabel><NativeSelect id={"filament-"+index} {...form.register(("materials."+index+".filamentId") as "materials.0.filamentId",{onChange:event=>{const filament=filaments.find(f=>f.id===event.target.value);if(filament)form.setValue(("materials."+index+".pricePerGram") as "materials.0.pricePerGram",decimalInput(filament.pricePerGram));}})}><NativeSelectOption value="">Seleccionar</NativeSelectOption>{filaments.map(f=><NativeSelectOption key={String(f.id)} value={String(f.id)}>{String(f.name??String(f.brand)+" "+String(f.model)+" · "+String(f.color))}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor={"grams-"+index}>Gramos *</FieldLabel><Input id={"grams-"+index} type="number" min="0.1" step="0.1" {...form.register(("materials."+index+".grams") as "materials.0.grams",{onBlur:event=>{if(event.target.value)form.setValue(("materials."+index+".grams") as "materials.0.grams",decimalInput(event.target.value));}})}/></Field><Field><FieldLabel htmlFor={"gram-price-"+index}>COP / g *</FieldLabel><Input id={"gram-price-"+index} type="number" min="0" step="0.1" {...form.register(("materials."+index+".pricePerGram") as "materials.0.pricePerGram",{onBlur:event=>{if(event.target.value)form.setValue(("materials."+index+".pricePerGram") as "materials.0.pricePerGram",decimalInput(event.target.value));}})}/></Field><div className="quote-line-subtotal"><span>Subtotal</span><strong>{(()=>{try{return money(new D(values.materials[index]?.grams||0).times(values.materials[index]?.pricePerGram||0).toString());}catch{return "—";}})()}</strong></div><Button aria-label={"Quitar material "+(index+1)} className="quote-remove-material" variant="ghost" size="icon" type="button" disabled={materials.fields.length===1} onClick={()=>materials.remove(index)}><Trash2 aria-hidden="true"/></Button></FieldGroup>)}<Button type="button" variant="outline" disabled={materials.fields.length>=100} onClick={()=>materials.append({filamentId:"",grams:"",pricePerGram:""})}><Plus data-icon="inline-start"/>Agregar otro filamento</Button></FieldGroup></CardContent></Card>
 <Card className="quote-time-card"><CardHeader><CardTitle>Tiempo de impresión</CardTitle><span className="quote-duration">{values.hours||0} h {values.minutes||0} min {values.seconds||0} s</span></CardHeader><CardContent><div className="quote-time-content"><FieldGroup className="time-fields">{text("hours","Horas","number")}{text("minutes","Minutos (0–59)","number")}{text("seconds","Segundos (0–59)","number")}</FieldGroup><details className="quote-formula-details"><summary>Variables y multiplicadores</summary><FieldGroup className="quote-variable-fields">{text("powerKw","Potencia (kW)","number")}{text("energyRate","Energía (COP / kWh)","number")}{text("machineRate","Máquina (COP / hora)","number")}{text("contingencyRate","Contingencia (0.10 = 10 %)","number")}<FieldGroup className="time-fields field-wide">{text("minimum","Mínimo ×","number")}{text("medium","Medio ×","number")}{text("high","Alto ×","number")}</FieldGroup></FieldGroup></details></div></CardContent></Card>
 <Card className="quote-postprocess-card"><CardHeader><CardTitle>Postprocesado</CardTitle><CardDescription>Se suma al costo antes de aplicar los multiplicadores.</CardDescription></CardHeader><CardContent><FieldGroup>{post.fields.map((row,index)=><FieldGroup key={row.id} className="postprocess-line"><Field><FieldLabel htmlFor={"pp-"+index}>Concepto *</FieldLabel><Input id={"pp-"+index} {...form.register(("postprocess."+index+".description") as "postprocess.0.description")}/></Field><Field><FieldLabel htmlFor={"pp-amount-"+index}>Costo (COP) *</FieldLabel><Input type="number" min="0" step="any" id={"pp-amount-"+index} {...form.register(("postprocess."+index+".amount") as "postprocess.0.amount")}/></Field><Button type="button" variant="ghost" onClick={()=>post.remove(index)}>Quitar acabado</Button></FieldGroup>)}<Button type="button" variant="outline" disabled={post.fields.length>=100} onClick={()=>post.append({description:"",category:"other",amount:""})}><Plus data-icon="inline-start"/>Agregar acabado o mano de obra</Button></FieldGroup></CardContent></Card>
 {preview&&<Card className="quote-price-card"><CardHeader><CardTitle>Elige el precio de venta</CardTitle><CardDescription>Selecciona una opción o escribe un precio manual. La utilidad se calcula después del costo de producción.</CardDescription></CardHeader><CardContent><div className="quote-price-options"><ToggleGroup aria-label="Precios de venta sugeridos" value={level&&!values.manualPrice?[level]:[]} onValueChange={v=>{key.current=null;publishKey.current=null;setCopied(false);form.setValue("manualPrice","");setLevel(String(v[0]??""));}} variant="outline">{preview.priceOptions.map(option=>{const label=({minimum:"Mínimo",medium:"Medio",high:"Alto"} as Record<string,string>)[option.level];const profit=new D(option.profit);const selected=level===option.level&&!values.manualPrice;return <ToggleGroupItem className="quote-price-option" aria-label={label+" · "+money(option.price)} key={option.level} value={option.level}><span className="quote-option-caption"><span>{label} <small>×{new D(option.multiplier).toString()}</small></span><span className="quote-option-check">{selected?<Check aria-hidden="true"/>:<span/>}</span></span><strong className="quote-option-amount">{money(option.price)}</strong><span className="quote-option-profit" data-tone={profit.isNegative()?"negative":profit.isPositive()?"positive":"neutral"}><TrendingUp aria-hidden="true"/><span>Utilidad <strong>{money(option.profit)}</strong></span></span><span className="quote-option-margin">{option.marginPercent===null?"Sin base para margen":oneDecimal(option.marginPercent)+" % de margen"}</span></ToggleGroupItem>;})}</ToggleGroup><div className="quote-manual-option" data-selected={!!values.manualPrice}><div className="quote-option-caption"><span>Tu propio precio</span>{!!values.manualPrice&&<span className="quote-manual-selected"><Check aria-hidden="true"/>Seleccionado</span>}</div>{text("manualPrice","Precio manual (COP)","number")}<div className="quote-option-profit" data-tone={values.manualPrice&&actualProfit?actualProfit.isNegative()?"negative":actualProfit.isPositive()?"positive":"neutral":"neutral"}><TrendingUp aria-hidden="true"/><span>Utilidad <strong>{values.manualPrice&&actualProfit?money(actualProfit.toString()):"—"}</strong></span></div><span className="quote-option-margin">{values.manualPrice?(actualMargin===null?"Sin base para margen":oneDecimal(actualMargin)+" % de margen"):"Escribe un valor para calcular su utilidad"}</span></div></div></CardContent></Card>}
 <Card className="quote-notes-card"><CardHeader><CardTitle>Notas y observaciones</CardTitle></CardHeader><CardContent><FieldGroup><Field><FieldLabel htmlFor="customer-notes">Notas para el cliente</FieldLabel><Textarea id="customer-notes" {...form.register("customerNotes")}/></Field><Field><FieldLabel htmlFor="internal-notes">Notas internas</FieldLabel><Textarea id="internal-notes" {...form.register("internalNotes")}/><FieldDescription>No se incluyen en el PDF del cliente.</FieldDescription></Field></FieldGroup></CardContent></Card></div>
 <aside className="quote-calculation"><Card className="quote-summary-card"><CardHeader><CardTitle>Resumen del cálculo</CardTitle><span className={actualPrice!==null?"quote-ready":"quote-incomplete"}>{actualPrice!==null?"Listo para cotizar":"Completa los datos"}</span></CardHeader><CardContent><dl className="calculation-summary">
 <div><dt><Layers aria-hidden="true"/>Material ({(()=>{try{return oneDecimal(values.materials.reduce((n,line)=>n.plus(line.grams||0),new D(0)).toString());}catch{return "—";}})()} g)</dt><dd>{preview?money(preview.components.material):"—"}</dd></div>
 <div><dt><Clock aria-hidden="true"/>Impresión ({values.hours||0} h {values.minutes||0} min){Number(values.seconds)>0?" "+values.seconds+" s":""}</dt><dd>{preview?money(new D(preview.components.energy).plus(preview.components.machine).toString()):"—"}</dd></div>
 <div><dt><Paintbrush aria-hidden="true"/>Postprocesado</dt><dd>{preview?money(preview.components.postprocess):"—"}</dd></div><div><dt><Coins aria-hidden="true"/>Contingencia</dt><dd>{preview?money(preview.components.contingency):"—"}</dd></div>
 {actualProfit!==null&&<div className="quote-profit" data-tone={actualProfit.isNegative()?"negative":actualProfit.isPositive()?"positive":"neutral"}><dt><TrendingUp aria-hidden="true"/>Utilidad{actualMargin!==null?" ("+new D(actualMargin).toString()+" %)":""}</dt><dd>{actualProfit.isPositive()?"+ ":""}{money(actualProfit.toString())}</dd></div>}
 </dl>
 <div className="quote-grand-total"><div className="quote-total-caption"><span>Total cotizado</span><span>Pesos colombianos</span></div><div className="quote-total-amount"><strong>{actualPrice===null?"—":money(actualPrice)}</strong><span>COP</span><span className="quote-tax-note">Sin impuestos</span></div></div>
 {actualProfit?.isNegative()&&<Alert variant="destructive"><AlertTitle>Precio inferior al costo</AlertTitle><AlertDescription>Esta cotización genera una pérdida estimada.</AlertDescription></Alert>}
 <Button className="quote-issue" data-intent="publish" type="submit" disabled={form.formState.isSubmitting} onClick={()=>{intent.current="publish";}}>{form.formState.isSubmitting?<Spinner data-icon="inline-start"/>:<Check data-icon="inline-start"/>}Guardar y emitir cotización</Button>
 <div className="quote-summary-actions">{quoteId&&revisionId&&<a className="quote-saved-pdf" href={"/api/quotes/"+quoteId+"/revisions/"+revisionId+"/pdf"} target="_blank" rel="noreferrer"><FileText aria-hidden="true"/><span>PDF guardado</span></a>}<Button type="button" variant="outline" disabled={actualPrice===null} onClick={async()=>{try{await navigator.clipboard.writeText("Cotización: "+values.projectName+"\nTotal: "+money(actualPrice)+" COP\n"+(values.customerNotes||""));setCopied(true);}catch{setError("No se pudo copiar el resumen.");}}}><Copy data-icon="inline-start"/>{copied?"Resumen copiado":"Copiar resumen"}</Button></div>
 <div className="quote-document-note"><Info aria-hidden="true"/><p>Costo de producción: <strong>{preview?money(preview.costProduction):"—"}</strong>.<br/>{quoteId&&revisionId?"El PDF corresponde a la versión guardada; guarda los cambios para actualizarlo.":"Guarda la cotización para descargar su PDF."}</p></div>
 </CardContent></Card>{error&&<Alert variant="destructive"><AlertTitle>No se pudo completar</AlertTitle><AlertDescription>{error}{savedId&&<Link className="inline-link" href={"/cotizaciones/"+savedId}> Abrir borrador guardado</Link>}</AlertDescription></Alert>}{form.formState.isSubmitted&&!form.formState.isValid&&<p role="alert" className="text-sm text-destructive">Revisa los campos obligatorios y las cantidades.</p>}</aside></form>;
}






