import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {CalendarDays,FileText,Box,Layers,TrendingUp,Clock,ShieldCheck,Scale,Coins,Calculator} from "lucide-react";
import type {ReactNode} from "react";
import {getEntityDetail,getCustomerOptions,getProvisionalOrderOptions} from "@/lib/app-service";
import {D} from "@/lib/finance";
import {QuoteDelete} from "@/components/quote-delete";
import {QuoteCreateOrder} from "@/components/quote-create-order";
import {CommandForm} from "@/components/command-form";
import {FilamentColor} from "@/components/filament-color";
import {money,display,oneDecimal,unitMoney} from "@/components/display";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";

function SectionTitle({icon,title,description}:{icon:ReactNode;title:string;description:string}){return <div className="quote-detail-section-title"><span className="quote-detail-icon">{icon}</span><div><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></div></div>;}
function Metric({icon,label,value,accent=false}:{icon:ReactNode;label:string;value:ReactNode;accent?:boolean}){return <div className={"quote-detail-metric"+(accent?" metric-gold":"")}><span>{icon}</span><div><dt>{label}</dt><dd>{value}</dd></div></div>;}
const tone=(value:InstanceType<typeof D>)=>value.isNegative()?"negative":value.isPositive()?"positive":"neutral";

export async function QuoteDetail({id}:{id:string}){
 let data;try{data=await getEntityDetail("quotes",id);}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar la cotización</AlertTitle><AlertDescription>Intenta de nuevo o solicita ayuda al administrador.</AlertDescription></Alert>;}
 const {item,related}=data;
 const revisionId=String(item.revisionId??""),status=String(item.status),code=String(item.code),quotePayload={quoteId:id,revisionId,expectedVersion:item.version};
 const client=item.clientSnapshot as Record<string,unknown>|null;
 const cost=new D(String(item.estimatedCost??0)),price=item.selectedPrice==null?null:new D(String(item.selectedPrice)),profit=price?.minus(cost),margin=price&&!price.isZero()&&profit?oneDecimal(profit.div(price).times(100).toString()):null;
 const snapshot=item.formulaSnapshot as {inputSnapshot?:{manualPrice?:string;selectedLevel?:string}}|null;
 const selectedLevel=snapshot?.inputSnapshot?.selectedLevel,manual=snapshot?.inputSnapshot?.manualPrice;
 const pdf=revisionId?`/api/quotes/${id}/revisions/${revisionId}/pdf`:null;
 const seconds=BigInt(String(item.printSeconds??0)),duration=`${seconds/3600n} h ${seconds%3600n/60n} min${seconds%60n?" "+seconds%60n+" s":""}`;
 const [customers,intakes]=status==="accepted"?await Promise.all([getCustomerOptions(),getProvisionalOrderOptions()]):[[],[]];
 return <div className="quote-detail-page"><PageHeader title={<>Cotización {code}</>} breadcrumbs={[{label:"Cotizaciones",href:"/cotizaciones"},{label:code}]} badges={<Badge data-status={status} variant="secondary">{status==="sent"?"Enviada al cliente":display(status)}</Badge>} description={<><CalendarDays aria-hidden="true"/>{item.validUntil?"Vigencia: "+String(item.validUntil):"Fecha comercial: "+String(item.businessDate)}</>} actions={<>{pdf&&<a className="app-header-link" href={pdf} target="_blank" rel="noreferrer"><FileText aria-hidden="true"/>Descargar PDF</a>}{status!=="accepted"&&<Link className="app-header-link app-header-primary" href={`/cotizaciones/${id}/editar`}>{status==="draft"?"Editar borrador":"Crear nueva revisión"}</Link>}</>}/>
 <div className="quote-detail-columns"><div className="quote-detail-main"><Card className="quote-project-overview"><CardHeader><SectionTitle icon={<Box/>} title="Información del proyecto" description="Detalles del encargo y versión comercial"/><span className="quote-revision-label">Revisión #{String(item.revisionNumber)} · Activa</span></CardHeader><CardContent><dl className="quote-project-overview-grid"><div><dt>Nombre de la pieza</dt><dd>{String(item.projectName)}</dd><small>{String(item.quantity??1)} {Number(item.quantity??1)===1?"pieza":"piezas"} · Precio unitario: {money(new D(String(item.quotedPrice??0)).div(String(item.quantity??1)).toString())}</small></div><div><dt>Cliente asignado</dt><dd>{client?.name?String(client.name):"Sin cliente asignado"}</dd></div><div><dt>Fecha de expedición</dt><dd>{String(item.businessDate)}</dd></div><div className="quote-project-description"><dt>Descripción técnica</dt><dd>{item.description?String(item.description):"Sin descripción registrada."}</dd></div><div className="quote-base-cost"><dt>Costo base de producción</dt><dd>{money(item.estimatedCost)} <small>COP</small></dd><span>Incluye material, energía, máquina y acabados</span></div></dl><div className="quote-detail-notes"><div><h3>Notas internas del taller</h3><p>{item.internalNotes?String(item.internalNotes):"Sin notas internas."}</p></div><div><h3>Notas para el cliente</h3><p>{item.customerNotes?String(item.customerNotes):"Sin notas para el cliente."}</p></div></div></CardContent></Card>
 <Card><CardHeader><SectionTitle icon={<Layers/>} title="Materiales y filamentos" description="Consumo y precios registrados en esta revisión"/></CardHeader><CardContent><div className="quote-detail-materials">{(related.materials??[]).map(line=>{const filament=line.filamentSnapshot as Record<string,unknown>;const subtotal=new D(String(line.grams)).times(String(line.pricePerGram));return <article key={String(line.id)} className="quote-detail-material"><div className="quote-detail-material-name"><strong>{[filament.brand,filament.model,filament.materialType].filter(Boolean).join(" · ")}</strong><FilamentColor value={filament.color}/></div><dl className="quote-material-metrics"><Metric icon={<Scale/>} label="Gramos presupuestados" value={oneDecimal(line.grams)+" g"}/><Metric icon={<Coins/>} label="Precio por gramo" value={unitMoney(line.pricePerGram)}/><Metric icon={<Calculator/>} label="Subtotal material" value={money(subtotal.toString())} accent/></dl>{!cost.isZero()&&<p className="quote-material-share">{oneDecimal(subtotal.div(cost).times(100).toString())} % del costo de producción</p>}</article>;})}</div></CardContent></Card>
 <Card><CardHeader><SectionTitle icon={<TrendingUp/>} title="Opciones de precio y márgenes" description="Escenarios de venta sobre el costo de producción"/></CardHeader><CardContent><div className="quote-detail-price-grid">{[...(related.priceOptions??[])].sort((a,b)=>new D(String(a.multiplier)).cmp(String(b.multiplier))).map(option=>{const optionProfit=new D(String(option.profitValue)),selected=!manual&&option.level===selectedLevel;return <article key={String(option.id)} className="quote-detail-price" data-selected={selected}><div className="quote-option-caption"><span>{({minimum:"Mínimo",medium:"Medio",high:"Alto"} as Record<string,string>)[String(option.level)]} <small>×{new D(String(option.multiplier)).toString()}</small></span>{selected&&<span>Elegido</span>}</div><strong>{money(option.price)}</strong><p data-tone={tone(optionProfit)}>Utilidad <b>{money(option.profitValue)}</b></p><small>{option.marginPercent==null?"Sin base para margen":oneDecimal(option.marginPercent)+" % de margen"}</small></article>;})}{manual&&price&&profit&&<article className="quote-detail-price" data-selected="true"><div className="quote-option-caption"><span>Precio manual</span><span>Elegido</span></div><strong>{money(price.toString())}</strong><p data-tone={tone(profit)}>Utilidad <b>{money(profit.toString())}</b></p><small>{margin===null?"Sin base para margen":margin+" % de margen"}</small></article>}</div></CardContent></Card>
 <Card><CardHeader><SectionTitle icon={<Clock/>} title="Impresión y costos" description={"Tiempo presupuestado: "+duration}/></CardHeader><CardContent><dl className="quote-detail-costs">{[["Material",item.materialCost],["Energía",item.energyCost],["Máquina",item.machineCost],["Contingencia",item.contingencyCost],["Postprocesado",item.postprocessCost]].map(([label,value])=><div key={String(label)}><dt>{String(label)}</dt><dd>{money(value)}</dd></div>)}</dl>{(related.postprocess??[]).length>0&&<div className="quote-detail-finishes">{related.postprocess.map(p=><div key={String(p.id)}><span>{String(p.description)}</span><strong>{money(p.estimatedAmount)}</strong></div>)}</div>}</CardContent></Card>
 {(related.revisions??[]).length>0&&<Card><CardHeader><SectionTitle icon={<FileText/>} title="Historial de revisiones" description="Documentos conservados de la cotización"/></CardHeader><CardContent><div className="quote-revision-history">{related.revisions.map(r=><div key={String(r.id)}><span>Revisión {String(r.revisionNumber)} <small>{display(r.status)}{r.id===revisionId?" · Activa":""}</small></span><strong>{money(r.quotedPrice)}</strong><a href={`/api/quotes/${id}/revisions/${r.id}/pdf`} target="_blank" rel="noreferrer">Descargar PDF de esta revisión</a></div>)}</div></CardContent></Card>}</div>
 <aside className="quote-commercial-sidebar"><Card className="quote-commercial-card"><CardHeader><CardTitle>Documento comercial</CardTitle><code>{code}</code></CardHeader><CardContent><div className="quote-commercial-total"><p>Precio final elegido al cliente</p><strong>{money(item.selectedPrice)} <small>COP</small></strong><dl><div><dt>Costo base de producción</dt><dd>{money(item.estimatedCost)}</dd></div>{profit&&<div className="quote-commercial-profit" data-tone={tone(profit)}><dt>Utilidad proyectada</dt><dd>{money(profit.toString())}{margin!==null&&<small>({margin} %)</small>}</dd></div>}</dl><span>Sin impuestos</span></div><div className="quote-commercial-actions">{status==="draft"&&<CommandForm command="quotes.publish" payload={quotePayload} label="Marcar enviada"/>}{status==="sent"&&<><div className="quote-accept-action"><CommandForm command="quotes.accept" payload={quotePayload} label="Aceptar cotización"/></div><div className="quote-reject-action"><CommandForm command="quotes.reject" payload={quotePayload} fields={[{name:"reason",label:"Motivo de rechazo",required:true}]} label="Rechazar"/></div></>}{status==="accepted"&&<QuoteCreateOrder quoteId={id} revisionId={revisionId} version={item.version} customerId={String(item.customerId??"")} customers={customers} intakes={intakes}/>}<div className="quote-duplicate-action"><CommandForm command="quotes.duplicate" payload={quotePayload} label="Duplicar y editar" redirectTo="/cotizaciones/:id/editar"/></div><QuoteDelete quoteId={id} revisionId={revisionId} version={item.version} code={code}/><div className="quote-commercial-links">{pdf&&<a href={pdf} target="_blank" rel="noreferrer"><FileText/>Descargar PDF para el cliente</a>}{status!=="accepted"&&<Link href={`/cotizaciones/${id}/editar`}>{status==="draft"?"Editar borrador":"Crear nueva revisión"}</Link>}</div></div></CardContent></Card><div className="quote-commercial-footnote"><ShieldCheck aria-hidden="true"/><p>Los importes pertenecen a esta revisión. El costo real se registra en el pedido durante la producción.</p></div></aside></div></div>;
}
