"use client";
import {PageHeader} from "@/components/page-header";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {action} from "@/app/actions";
import {authClient} from "@/lib/auth-client";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Field,FieldGroup,FieldLabel,FieldDescription} from "@/components/ui/field";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "@/components/ui/card";
import {Zap,Coins,Clock3,ShieldCheck,RotateCcw,Save,Calculator,History,Check,SlidersHorizontal,TrendingUp} from "lucide-react";
import {defaultFormula,D,formulaSchema,cop} from "@/lib/finance";

function plain(value:string){return new D(value).toString();}
function readable(value:string){return new Intl.NumberFormat("es-CO",{maximumFractionDigits:6}).format(Number(value));}
export function SettingsForm({formula=defaultFormula,version,updatedAt,updatedBy}:{formula?:typeof defaultFormula;version:unknown;updatedAt?:string;updatedBy?:string}){
 const router=useRouter();
 const [values,setValues]=useState(()=>({powerKw:plain(formula.powerKw),energyRate:plain(formula.energyRate),machineRate:plain(formula.machineRate),contingencyRate:plain(formula.contingencyRate),minimum:plain(formula.multipliers[0]),medium:plain(formula.multipliers[1]),high:plain(formula.multipliers[2])}));
 const [pending,setPending]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const currentVersion=useRef(Number(version)),requestKey=useRef<string|null>(null);
 const next={powerKw:values.powerKw,energyRate:values.energyRate,machineRate:values.machineRate,contingencyRate:values.contingencyRate,multipliers:[values.minimum,values.medium,values.high]};
 const valid=formulaSchema.safeParse(next).success;
 const number=(value:string)=>/^\d+(\.\d+)?$/.test(value)&&Number.isFinite(Number(value))?new D(value):null;
 const power=number(values.powerKw),energy=number(values.energyRate),machine=number(values.machineRate),contingency=number(values.contingencyRate);
 const hourly=power&&energy&&machine?power.times(energy).plus(machine):null;
 function change(name:keyof typeof values,value:string){setValues(old=>({...old,[name]:value}));setMessage("");setError("");requestKey.current=null;}
 function reset(){setValues({powerKw:defaultFormula.powerKw,energyRate:defaultFormula.energyRate,machineRate:defaultFormula.machineRate,contingencyRate:defaultFormula.contingencyRate,minimum:defaultFormula.multipliers[0],medium:defaultFormula.multipliers[1],high:defaultFormula.multipliers[2]});setMessage("Valores iniciales cargados. Guarda para aplicarlos.");setError("");requestKey.current=null;}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending)return;setError("");setMessage("");if(!valid){setError("Revisa los valores: la contingencia debe estar entre 0 y 1 y los multiplicadores deben ser positivos y estar ordenados de menor a mayor.");return;}setPending(true);requestKey.current??=crypto.randomUUID();try{const result=await action("settings.update",{formula:next,expectedVersion:currentVersion.current,idempotencyKey:requestKey.current});if(result.ok){currentVersion.current+=1;requestKey.current=null;setMessage("Parámetros guardados. Se aplican a nuevas cotizaciones.");router.refresh();}else{setError(result.error.message);}}catch{setError("No pudimos confirmar el guardado. Intenta de nuevo.");}finally{setPending(false);}}
 const save=<Button form="workshop-settings" type="submit" disabled={pending}><Save aria-hidden="true"/>{pending?"Guardando…":"Guardar parámetros"}</Button>;
 return <div className="workshop-settings-page">
 <PageHeader title="Ajustes" breadcrumbs={[{label:"Ajustes"}]} description="Valores predeterminados para nuevas cotizaciones." actions={<><Button variant="outline" onClick={reset} disabled={pending}><RotateCcw aria-hidden="true"/>Restablecer valores iniciales</Button>{save}</>}/>
 <section className="settings-reference-metrics" aria-label="Resumen de parámetros">{[{label:"Potencia eléctrica",value:power?readable(power.toString()):"—",unit:"kW",help:power?`${readable(power.times(1000).toString())} W de potencia promedio`:"Completa la potencia",icon:Zap},{label:"Tarifa de energía",value:energy?cop(energy.toString()):"—",unit:"COP / kWh",help:"Costo de electricidad",icon:Coins},{label:"Máquina por hora",value:machine?cop(machine.toString()):"—",unit:"COP / h",help:"Desgaste y uso del equipo",icon:Clock3},{label:"Contingencia",value:contingency?`${readable(contingency.times(100).toString())} %`:"—",unit:"del material",help:"Recargo sobre el costo de filamento",icon:ShieldCheck}].map(m=><Card key={m.label}><CardContent><div><span>{m.label}</span><m.icon aria-hidden="true"/></div><p><strong>{m.value}</strong><small>{m.unit}</small></p><span className="settings-metric-help">{m.help}</span></CardContent></Card>)}</section>
 <form id="workshop-settings" className="settings-reference-form" onSubmit={submit}>
 <Card className="settings-reference-section"><CardHeader><div><CardTitle><SlidersHorizontal aria-hidden="true"/>Variables de costos del taller</CardTitle><CardDescription>Consumo eléctrico, uso de máquina y contingencia.</CardDescription></div><span className="settings-section-tag">Costos base</span></CardHeader><CardContent><FieldGroup className="settings-base-fields">{[{name:"powerKw" as const,label:"Potencia promedio (kW)",unit:"kW",help:"Ej. 0.15 kW = 150 W."},{name:"energyRate" as const,label:"Energía (COP / kWh)",unit:"COP/kWh",help:"Tarifa de tu recibo de electricidad."},{name:"machineRate" as const,label:"Máquina (COP / hora)",unit:"COP/h",help:"Costo por cada hora de impresión."},{name:"contingencyRate" as const,label:"Contingencia (0.10 = 10 %)",unit:"factor",help:"Se aplica solo al material."}].map(f=><Field key={f.name}><FieldLabel htmlFor={`settings-${f.name}`}>{f.label} *</FieldLabel><div className="settings-unit-input"><Input id={`settings-${f.name}`} name={f.name} type="number" min="0" max={f.name==="contingencyRate"?"1":undefined} step="any" value={values[f.name]} onChange={e=>change(f.name,e.currentTarget.value)} required disabled={pending} aria-describedby={`settings-help-${f.name}`}/><span aria-hidden="true">{f.unit}</span></div><FieldDescription id={`settings-help-${f.name}`}>{f.help}</FieldDescription></Field>)}</FieldGroup><div className="settings-hourly-bar"><div><Calculator aria-hidden="true"/><span>Costo por hora de impresión</span><strong>{hourly?cop(hourly.toString()):"—"} <small>COP / h</small></strong></div><p>{power&&energy&&machine?`${readable(power.toString())} kW × ${cop(energy.toString())} + ${cop(machine.toString())}`:"Completa potencia, energía y máquina."} · Excluye material y acabados.</p></div></CardContent></Card>
 <Card className="settings-reference-section"><CardHeader><div><CardTitle><TrendingUp aria-hidden="true"/>Multiplicadores de venta</CardTitle><CardDescription>Se aplican al costo de producción completo, incluidos los acabados.</CardDescription></div><span className="settings-section-tag">3 precios sugeridos</span></CardHeader><CardContent><div className="settings-multiplier-grid">{[{name:"minimum" as const,label:"Mínimo",description:"Primer precio sugerido",tag:"Base"},{name:"medium" as const,label:"Medio",description:"Precio seleccionado inicialmente",tag:"Predeterminado"},{name:"high" as const,label:"Alto",description:"Tercer precio sugerido",tag:"Superior"}].map(f=>{const multiplier=number(values[f.name]);const margin=multiplier&&multiplier.gt(0)?multiplier.minus(1).div(multiplier).times(100):null;return <div className="settings-multiplier" data-level={f.name} key={f.name}><div className="settings-multiplier-heading"><strong>{f.label}</strong><span>{f.tag}</span></div><p>{f.description}</p><Field><FieldLabel htmlFor={`settings-${f.name}`}>Multiplicador {f.label.toLowerCase()} *</FieldLabel><div className="settings-unit-input"><Input id={`settings-${f.name}`} name={f.name} type="number" min="0.000001" step="any" required disabled={pending} value={values[f.name]} onChange={e=>change(f.name,e.currentTarget.value)}/><span aria-hidden="true">×</span></div></Field><div className="settings-margin"><span>Margen bruto aproximado</span><strong data-negative={margin?.isNegative()??false}>{margin?`${margin.toFixed(1).replace(".",",")} %`:"—"}</strong></div></div>;})}</div></CardContent></Card>
 <div className="settings-formula-band"><div><span>Fórmula Golden Print 3D</span><p>Costo de producción = material + energía + máquina + contingencia + postprocesado</p><small>Material = gramos × COP/g · Energía = horas × kW × COP/kWh · Máquina = horas × COP/h · Contingencia = material × factor</small><p className="settings-price-formula">Precio sugerido = costo de producción × multiplicador</p></div>{save}</div>
 {error&&<Alert variant="destructive"><AlertTitle>No se pudo guardar</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{message&&<div className="settings-save-feedback" role="status"><Check aria-hidden="true"/>{message}</div>}
 </form>
 <div className="settings-reference-notes"><Card><CardContent><ShieldCheck aria-hidden="true"/><div><strong>Cotizaciones anteriores protegidas</strong><p>Los nuevos parámetros se aplican a futuras cotizaciones. Las guardadas conservan los valores con los que se crearon.</p></div></CardContent></Card><Card><CardContent><History aria-hidden="true"/><div><strong>Última actualización</strong><p>{updatedAt?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Bogota"}).format(new Date(updatedAt)).replace(/\s/g," "):"Sin fecha registrada"}{updatedBy?` · ${updatedBy}`:""}</p></div></CardContent></Card></div>
 </div>;
}
export function PasswordForm(){const[pending,setPending]=useState(false);const[error,setError]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setPending(true);try{const result=await authClient.changePassword({currentPassword:String(fd.get("currentPassword")),newPassword:String(fd.get("newPassword")),revokeOtherSessions:true});setError(result.error?"No se pudo cambiar la contraseña. Revisa los datos.":"Contraseña actualizada.");}catch{setError("No pudimos conectar. Intenta de nuevo.");}finally{setPending(false);}}return <form className="settings-form flex flex-col gap-5" onSubmit={submit}><FieldGroup><Field><FieldLabel htmlFor="own-current">Contraseña actual</FieldLabel><Input id="own-current" name="currentPassword" type="password" autoComplete="current-password" required disabled={pending}/></Field><Field><FieldLabel htmlFor="own-new">Nueva contraseña</FieldLabel><Input id="own-new" name="newPassword" type="password" autoComplete="new-password" minLength={12} required disabled={pending}/></Field></FieldGroup>{error&&<Alert><AlertTitle>Cambio de contraseña</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<Button type="submit" disabled={pending}>Cambiar contraseña</Button></form>;}
