import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {UserRound,ShieldCheck,Mail,CalendarDays,KeyRound,History,LockKeyhole,Check,CircleCheck,Ban,Info,UserCog} from "lucide-react";
import {getEntityDetail} from "@/lib/app-service";
import {CommandForm} from "@/components/command-form";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "@/components/ui/card";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
const dates=(value:unknown,time=false)=>new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",...(time?{timeStyle:"short" as const}:{}),timeZone:"America/Bogota"}).format(new Date(String(value)));
const auditLabels:Record<string,string>={"users.create":"Usuario creado","users.updateName":"Nombre actualizado","users.changeRole":"Rol actualizado","users.deactivate":"Acceso desactivado","users.reactivate":"Acceso reactivado","users.resetCredential":"Contraseña restablecida"};
export async function UserDetail({id}:{id:string}){
 let data;try{data=await getEntityDetail("users",id);}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar el usuario</AlertTitle><AlertDescription>Vuelve al listado e intenta de nuevo con una cuenta administradora.</AlertDescription></Alert>;}
 const {item,related,access}=data,admin=item.role==="administrator",active=Boolean(item.active),last=Boolean(item.lastAdministrator),self=access.userId===id;
 const payload={targetUserId:id,expectedVersion:item.version},role=admin?"Administrador":"Operador",initials=String(item.name).trim().split(/\s+/).slice(0,2).map(w=>w[0]).join("").toUpperCase();
 return <div className="user-detail-page">
 <PageHeader title={String(item.name)} breadcrumbs={[{label:"Usuarios",href:"/usuarios"},{label:"Detalle del usuario"}]} badges={<><span className="user-role" data-role={String(item.role)}>{role}</span><span className="user-access-status" data-active={active}><span/>{active?"Acceso activo":"Acceso desactivado"}</span>{self&&<span className="user-own-account">Tu cuenta</span>}</>} actions={<a className="app-header-link" href="#user-name-edit">Editar nombre<UserRound aria-hidden="true"/></a>}/>
 <section className="user-detail-metrics" aria-label="Resumen del usuario">{[{label:"Rol actual",value:role,detail:"Permisos asignados en el taller",icon:ShieldCheck},{label:"Correo registrado",value:String(item.email),detail:"Correo utilizado para iniciar sesión",icon:Mail},{label:"Estado de acceso",value:active?"Activo":"Desactivado",detail:active?"Puede ingresar a la empresa":"No puede ingresar a la empresa",icon:active?CircleCheck:Ban,tone:active?"positive":"negative"},{label:"Miembro desde",value:dates(item.createdAt),detail:"Fecha de alta en la empresa",icon:CalendarDays}].map(({label,value,detail,icon:Icon,tone})=><article key={label} data-tone={tone}><header><span>{label}</span><Icon aria-hidden="true"/></header><strong>{value}</strong><p>{detail}</p></article>)}</section>
 <div className="user-detail-columns"><div className="user-detail-main"><Card className="user-profile-card"><CardHeader><CardTitle><UserRound aria-hidden="true"/>Información del perfil</CardTitle></CardHeader><CardContent><div className="user-profile-identity"><span className="user-profile-avatar">{initials}</span><div><h2>{String(item.name)}</h2><p>{String(item.email)}</p><span className="user-role" data-role={String(item.role)}>{role}</span></div></div><dl><div><dt>Correo de acceso</dt><dd>{String(item.email)}</dd></div><div><dt>Rol del taller</dt><dd>{role}</dd></div><div><dt>Alta en la empresa</dt><dd>{dates(item.createdAt)}</dd></div><div><dt>Última actualización del perfil</dt><dd>{dates(item.updatedAt,true)}</dd></div></dl><div id="user-name-edit"><h3>Editar nombre</h3><CommandForm command="users.updateName" payload={payload} fields={[{name:"name",label:"Nombre",value:String(item.name),required:true}]} label="Guardar nombre"/></div></CardContent></Card>
 <Card className="user-detail-permissions"><CardHeader><div><CardTitle><ShieldCheck aria-hidden="true"/>Permisos del rol</CardTitle><CardDescription>{active?"Accesos disponibles según el rol asignado.":"La cuenta está desactivada. Estos permisos se aplican al reactivarla."}</CardDescription></div></CardHeader><CardContent>{[{label:"Operación del taller",description:"Clientes, filamentos, cotizaciones y pedidos",allowed:true},{label:"Finanzas y gastos",description:"Reportes financieros, gastos, cobros y pérdidas",allowed:admin},{label:"Usuarios y permisos",description:"Creación de cuentas, roles y recuperación de acceso",allowed:admin},{label:"Ajustes de empresa",description:"Configuración general del taller",allowed:admin}].map(({label,description,allowed})=><article key={label} data-allowed={allowed}>{allowed?<Check aria-hidden="true"/>:<LockKeyhole aria-hidden="true"/>}<div><strong>{label}</strong><p>{description}</p></div><span>{allowed?"Permitido":"Restringido"}</span></article>)}</CardContent></Card>
 <Card className="user-detail-audit"><CardHeader><CardTitle><History aria-hidden="true"/>Historial de cambios del usuario</CardTitle></CardHeader><CardContent>{related.audit?.length?<ol>{related.audit.map(event=>{const meta=event.metadata as Record<string,unknown>;return <li key={String(event.id)}><strong>{auditLabels[String(event.action)]??"Acceso actualizado"}</strong><span>{dates(event.occurredAt,true)} · {String(event.actorName)}</span>{event.action==="users.updateName"&&<p>{String(meta.previousName)} → {String(meta.name)}</p>}</li>;})}</ol>:<p className="user-no-history">Aún no hay cambios de acceso registrados para este usuario.</p>}</CardContent></Card>
 </div><aside className="user-detail-actions"><Card><CardHeader><CardTitle><UserCog aria-hidden="true"/>Gestión de rol y acceso</CardTitle></CardHeader><CardContent><CommandForm command="users.changeRole" payload={payload} fields={[{name:"role",label:"Rol",value:String(item.role),required:true,options:last?[{value:"administrator",label:"Administrador"}]:[{value:"administrator",label:"Administrador"},{value:"operator",label:"Operador"}]}]} label="Cambiar rol"/><div className="user-access-management"><h3>Estado de acceso</h3><p>{active?"El usuario puede iniciar sesión con los permisos de su rol.":"El usuario tiene el acceso desactivado."}</p>{last?<div className="user-last-admin"><ShieldCheck aria-hidden="true"/><span>Es el último administrador activo. Crea o activa otro administrador antes de cambiar su rol o desactivar su acceso.</span></div>:<CommandForm command={active?"users.deactivate":"users.reactivate"} payload={payload} label={active?"Desactivar acceso":"Reactivar acceso"}/>}</div></CardContent></Card>
 <Card className="user-password-card"><CardHeader><div><CardTitle><KeyRound aria-hidden="true"/>Seguridad y contraseña</CardTitle><CardDescription>Restablece la contraseña si el usuario necesita recuperar su acceso.</CardDescription></div></CardHeader><CardContent><CommandForm command="users.resetCredential" payload={payload} fields={[{name:"password",label:"Nueva contraseña",type:"password",required:true,help:"Entre 12 y 128 caracteres."}]} label="Restablecer contraseña"/><p>La nueva contraseña cierra las sesiones abiertas de esta cuenta.</p></CardContent></Card>
 <div className="user-access-caution"><Info aria-hidden="true"/><div><strong>Control de acceso</strong><p>{self?"Estás administrando tu propia cuenta. Cambiar el rol, desactivar el acceso o restablecer la contraseña cierra tu sesión.":"Los cambios de rol y contraseña cierran las sesiones del usuario. Desactivar el acceso conserva sus registros del taller."}</p></div></div></aside></div></div>;
}
