"use client";
import {useState} from "react";
import Link from "next/link";
import {Search,LayoutGrid,List,ArrowRight,ChevronLeft,ChevronRight,Users} from "lucide-react";
import type {UserSummary} from "@/lib/users";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {ToggleGroup,ToggleGroupItem} from "@/components/ui/toggle-group";
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from "@/components/ui/table";
const roleLabel=(role:string)=>role==="administrator"?"Administrador":"Operador";
function Identity({user,currentId}:{user:UserSummary;currentId:string}){return <div className="user-identity"><span className="user-avatar" data-role={user.role}>{user.name.trim().split(/\s+/).slice(0,2).map(w=>w[0]).join("").toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.id===currentId?"Tu cuenta":"Miembro del taller"}</small></div></div>;}
function Status({active}:{active:boolean}){return <span className="user-access-status" data-active={active}><span/>{active?"Activo":"Desactivado"}</span>;}
export function UsersDirectory({users,currentId,initialQuery="",initialRole=""}:{users:UserSummary[];currentId:string;initialQuery?:string;initialRole?:string}){
 const [query,setQuery]=useState(initialQuery),[search,setSearch]=useState(initialQuery),[role,setRole]=useState(initialRole),[access,setAccess]=useState(""),[view,setView]=useState("table"),[page,setPage]=useState(1);
 const filtered=users.filter(u=>(!role||u.role===role)&&(!access||String(u.active)===(access==="active"?"true":"false"))&&[u.name,u.email].some(v=>v.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es"))));
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages),rows=filtered.slice((current-1)*10,current*10);
 return <section className="users-directory" aria-label="Directorio de usuarios"><div className="users-toolbar"><form onSubmit={e=>{e.preventDefault();setSearch(query.trim());setPage(1);}}><Search aria-hidden="true"/><Input aria-label="Buscar usuarios" placeholder="Buscar por nombre o correo" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="outline" type="submit">Buscar</Button></form><div><NativeSelect aria-label="Filtrar por rol" value={role} onChange={e=>{setRole(e.target.value);setPage(1);}}><NativeSelectOption value="">Todos los roles</NativeSelectOption><NativeSelectOption value="administrator">Administrador</NativeSelectOption><NativeSelectOption value="operator">Operador</NativeSelectOption></NativeSelect><NativeSelect aria-label="Filtrar por acceso" value={access} onChange={e=>{setAccess(e.target.value);setPage(1);}}><NativeSelectOption value="">Todos los accesos</NativeSelectOption><NativeSelectOption value="active">Activos</NativeSelectOption><NativeSelectOption value="inactive">Desactivados</NativeSelectOption></NativeSelect><ToggleGroup aria-label="Vista de usuarios" variant="outline" value={[view]} onValueChange={v=>{if(v[0])setView(String(v[0]));}}><ToggleGroupItem value="table"><List aria-hidden="true"/>Tabla</ToggleGroupItem><ToggleGroupItem value="cards"><LayoutGrid aria-hidden="true"/>Tarjetas</ToggleGroupItem></ToggleGroup></div></div>
 {rows.length?view==="table"?<div className="users-table"><Table><TableHeader><TableRow><TableHead>Usuario</TableHead><TableHead>Correo electrónico</TableHead><TableHead>Rol</TableHead><TableHead>Acceso</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{rows.map(u=><TableRow key={u.id}><TableCell><Identity user={u} currentId={currentId}/></TableCell><TableCell>{u.email}</TableCell><TableCell><span className="user-role" data-role={u.role}>{roleLabel(u.role)}</span></TableCell><TableCell><Status active={u.active}/></TableCell><TableCell><Link className="user-manage" href={`/usuarios/${u.id}`}>Gestionar acceso<ArrowRight aria-hidden="true"/></Link></TableCell></TableRow>)}</TableBody></Table></div>:<div className="users-cards">{rows.map(u=><article key={u.id}><Identity user={u} currentId={currentId}/><p>{u.email}</p><div><span className="user-role" data-role={u.role}>{roleLabel(u.role)}</span><Status active={u.active}/></div><Link className="user-manage" href={`/usuarios/${u.id}`}>Gestionar acceso<ArrowRight aria-hidden="true"/></Link></article>)}</div>:<div className="users-empty"><Users aria-hidden="true"/><strong>No hay usuarios con estos filtros</strong><p>Prueba otro nombre, rol o estado de acceso.</p></div>}
 <footer><Button variant="outline" disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft aria-hidden="true"/>Anterior</Button><span>{filtered.length} usuarios · Página {current} de {pages}</span><Button variant="outline" disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente<ChevronRight aria-hidden="true"/></Button></footer></section>;
}
