import {PageHeader} from "@/components/page-header";
import {Users,ShieldCheck,UserCheck,UserCog,UserPlus,Check,LockKeyhole,Info} from "lucide-react";
import {listUsers} from "@/lib/users";
import {requireAccess} from "@/lib/access";
import {UsersDirectory} from "@/components/users-directory";
import {CommandForm} from "@/components/command-form";
import {Card,CardHeader,CardTitle,CardContent,CardDescription} from "@/components/ui/card";
import {Alert,AlertTitle,AlertDescription} from "@/components/ui/alert";
export async function UsersPage({q="",filter=""}:{q?:string;filter?:string}){
 let users,access;try{access=await requireAccess("administrator");users=await listUsers();}catch{return <Alert variant="destructive"><AlertTitle>No pudimos cargar los usuarios</AlertTitle><AlertDescription>Esta página requiere un administrador con acceso activo.</AlertDescription></Alert>;}
 const active=users.filter(u=>u.active).length,admins=users.filter(u=>u.active&&u.role==="administrator").length,operators=users.filter(u=>u.active&&u.role==="operator").length;
 return <div className="users-page"><PageHeader title="Usuarios y permisos" breadcrumbs={[{label:"Usuarios"}]} description="Miembros del equipo y acceso a la empresa." actions={<a className="app-header-link" href="#create-user"><UserPlus aria-hidden="true"/>Nuevo miembro</a>}/>
 <section className="users-indicators" aria-label="Resumen de usuarios">{[{label:"Usuarios registrados",value:users.length,detail:`${users.length-active} con acceso desactivado`,icon:Users,tone:"neutral"},{label:"Accesos activos",value:active,detail:"Miembros autorizados para ingresar",icon:UserCheck,tone:"positive"},{label:"Administradores activos",value:admins,detail:"Control financiero y gestión de accesos",icon:ShieldCheck,tone:"gold"},{label:"Operadores activos",value:operators,detail:"Operación diaria del taller",icon:UserCog,tone:"info"}].map(({label,value,detail,icon:Icon,tone})=><article key={label} data-tone={tone}><header><h2>{label}</h2><Icon aria-hidden="true"/></header><strong>{value}</strong><p>{detail}</p></article>)}</section>
 <div className="users-workspace"><div className="users-main"><UsersDirectory users={users} currentId={access.userId} initialQuery={q} initialRole={["administrator","operator"].includes(filter)?filter:""}/>
 <Card className="user-permissions"><CardHeader><div><CardTitle><ShieldCheck aria-hidden="true"/>Roles y permisos del taller</CardTitle><CardDescription>Los permisos se asignan según el rol del usuario.</CardDescription></div><span>2 roles disponibles</span></CardHeader><CardContent><div className="user-permission-grid"><article><h3><ShieldCheck aria-hidden="true"/>Administrador</h3><p>Gestiona la operación del taller y la administración de la empresa.</p><ul><li><Check aria-hidden="true"/>Clientes, filamentos, cotizaciones y pedidos</li><li><Check aria-hidden="true"/>Finanzas, gastos, cobros y pérdidas</li><li><Check aria-hidden="true"/>Usuarios, roles y recuperación de acceso</li><li><Check aria-hidden="true"/>Ajustes de la empresa</li></ul><span>Administración del taller</span></article><article><h3><UserCog aria-hidden="true"/>Operador</h3><p>Trabaja con los proyectos y los registros de la operación diaria.</p><ul><li><Check aria-hidden="true"/>Clientes y catálogo de filamentos</li><li><Check aria-hidden="true"/>Cotizaciones y pedidos</li><li><Check aria-hidden="true"/>Seguimiento de producción</li><li><LockKeyhole aria-hidden="true"/>Sin acceso a Finanzas, Gastos, Usuarios ni Ajustes</li></ul><span>Operación del taller</span></article></div></CardContent></Card></div>
 <aside className="users-sidebar"><Card id="create-user" className="user-create"><CardHeader><div><CardTitle><UserPlus aria-hidden="true"/>Crear usuario</CardTitle><CardDescription>Registra un miembro con acceso a tu empresa.</CardDescription></div></CardHeader><CardContent><CommandForm command="users.create" label="Crear usuario" fields={[{name:"name",label:"Nombre",required:true},{name:"email",label:"Correo",type:"email",required:true},{name:"password",label:"Contraseña inicial",type:"password",required:true,help:"Entre 12 y 128 caracteres."},{name:"role",label:"Rol",value:"operator",required:true,options:[{value:"operator",label:"Operador"},{value:"administrator",label:"Administrador"}]}]}/></CardContent></Card><div className="users-access-note"><Info aria-hidden="true"/><div><strong>Control del acceso</strong><p>Desde “Gestionar acceso” puedes cambiar el rol, desactivar o reactivar una cuenta y restablecer su contraseña.</p><p>Debe permanecer al menos un administrador activo.</p></div></div></aside></div></div>;
}
